project:
  type: website
  output-dir: docs

website:
  title: "Governance Watch"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer:
    left: "© 2025 Dorj N."
    right: "Built with Quarto"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



