project:
  type: website

website:
  title: "alpha2zero"
  navbar:
    left:
      - href: index.qmd
        text: Нүүр
      - href: sectors.qmd
        text: Салбар
      - href: issues.qmd
        text: Сэдэв
      - href: about.qmd
        text: Тухай
      

format:
  html:
    theme: 
      - default
      - theme.scss
    toc: true



