project:
  type: website
  output-dir: "docs"

website:
  navbar:
    title: Alpha → Zero
    right:
      - href: index.qmd
        text: Нүүр
      - href: topics.qmd
        text: Сэдэв
      - href: events.qmd
        text: Үйл явдал
      - href: about.qmd
        text: Тухай

format:
  html:
    toc: true
    date-format: "YYYY-MM-DD"

language:
  title-block-published: "Нийтлэгдсэн"
  title-block-author-single: "Зохиогч"
  title-block-author-plural: "Зохиогчид"
  title-block-category: "Ангилал"
  listing-page-category-all: "Бүгд"
  toc-title-website: "Энэ хэсэгт:"
  