project:
  type: website
  output-dir: "docs"

website:
  navbar:
    title: |
      <span class="logo-alpha">Alpha</span>
      <span class="logo-arrow">→</span>
      <span class="logo-zero">Zero</span>
    right:
      - href: index.qmd
        text: Нүүр
      - href: topics.qmd
        text: Сэдэв
      - href: events.qmd
        text: Үйл явдал
      - href: about.qmd
        text: Тухай
  google-analytics: G-7Y3C1KYLKS

format:
  html:
    toc: true
    date-format: "YYYY-MM-DD"

language:
  title-block-published: "Нийтлэгдсэн"
  title-block-author-single: "Зохиогч"
  title-block-author-plural: "Зохиогчид"
  title-block-category: "Ангилал"
  listing-page-category-all: "Бүгд"
  toc-title-website: "Энэ хэсэгт:"
  