---
title: "Өгөгдлийн шинжилгээ"
format: 
  html: 
    theme: [default, theme-sectors.scss]
    warning: false
    echo: false
---

```{r}
library(tidyverse)
```

## Миний туршлага

Ил тод байдал нь мэдээллийг нээлттэй болгох эхний алхам. Харин тэр мэдээллийг ойлгож, шинжилж, бусдад ойлгомжтойгоор хүргэж чадсан үед л ил тод байдал бодит үр дүнгээ өгдөг. Энэ хэсэгт өгөгдөлтэй ажиллах туршлагаасаа хуваалцах, бусдаас суралцахыг зорих болно. Basic, Supercalc, DBase, Pascal зэргийг бага сага заалгаж байсан миний хувьд эдийн засгийн судалгаанд Эксел, эдийн засгийн чиглэлийн EViews, Stata, SPSS гэх мэт программыг суралцаж байв. Зарим нэгэн дүн шинжилгээг Crystal Ball зэрэг Экселийн нэмэлтийг ашиглан хийж үзсэн. Гагцхүү заримыг нь сайн сураагүй, заримыг нь хэсэг хугацаанд ашиглахгүй бол сурснаа мартах зэрэг асуудал үүсэж байв. Мөн эдгээр бүх програм нь үнэ төлбөртэй тул хүндрэлтэй.

Ковид цар тахлын үеэр би R программыг сонирхон сурах болов. Хэдий гүнзгий сураагүй ч өгөгдөлтэй ажиллах, дүрсжүүлэхэд ихээхэн тохиромжтой гэдгийг мөдхөн олж мэдсэн. Улмаар RMarkdown-ыг ашиглан өгөгдөл, текстэн тайланг бэлдэх нь ажлыг хялбарчлах юм гэж бодох болов. Сүүлд Quarto-г R-тай хослуулснаар өгөгдөл, тайлан, танилцуулга зэргийг хийх арга маань бүхэлдээ өөрчлөгдсөн. Тиймээс энд би Quarto, R, Эксел-тэй холбоотой зарим туршлагаасаа хуваалцах болно.

Тухайлбал:

- Excel ашиглан өгөгдөл боловсруулах, санхүүгийн загвар хийх;
- R Studio дээр R программыг ашиглан өгөгдлийн шинжилгээ, дүрслэл хийх, тухайлбал
  - tidyverse багцыг ашиглах;
  - ggplot2 багцыг ашиглан чанартай график, дүрслэл хийх;
  - gt багцаар мэргэжлийн түвшний хүснэгт бүтээх;
  - Quarto ашиглан давтагдах боломжтой, автомат шинэчлэгддэг тайлан болон вэб хуудас боловсруулах тухай бичье гэж шийдэв.

Би эдийн засагч, харин компьютерийн талын хүн биш гэдгийг та бүхэн ойлгоно гэдэгт итгэж байна.

## Суурь ойлголтууд

### R, R Studio

R гэдэн нь нээлттэй программын хэл. Өөрөөр хэлбэл, хэн ч хувь нэмрээ оруулах боломжтой, мөн хэн ч үнэ төлбөргүй ашиглах боломжтой. Анх статистикчид зохиосон байдаг. Хэдийн хэрэглээний хувьд Python гэх зэрэг программын хэлээс цөөн тооны хэрэглэгчтэй ч өнөөг хүртэл байнга шинэчлэгдэж, боломжууд нь байнга нэмэгдэж байдгаас гадна программист бус хүн хэрэглэх, сурахад ихээхэн дөхөм юм. R программыг шууд хэрэглэх нь их ховор, R Studio зэрэг завсрын программыг ашиглан кодоо бичиж, үр дүнг нь гарган авдаг. R Studio нь анхлан R хэлд зориулагдсан тул хослуулан ашиглахад их хялбар. Мөн сүүлийн үед хурдан түгэж буй Quarto-ийн хувьд R Studio-ийн нэгээхэн хэсэг болдог тул өгөгдөлтэй ажиллах, текст оруулах, тайланг олон хэлбэрээр бэлдэх зэрэгт ихээхэн тохиромжтой. R программын онцлог нь хэн нэгнийг хийсэн нэмэлт программуудыг татаж авч ашиглах боломжтой байдаг бөгөөд үүнийг багц (package) буюу сан (library) гэж нэрлэх нь бий.

### Tidyverse

tidyverse гэдэг нь өгөгдлийг R орчин руу татах, боловсруулах, хувиргах, дүрслэх зэрэг үндсэн боломжийг агуулсан хэд хэдэн багцыг нэгтгээд нэг багц болгон дуудаж, ажиллахад зориулагдсан "багцуудын багц" юм. Энд tidy буюу цэвэр гэх үгийг хэрэглэсэн нь ч учиртай. Өгөгдлийг ажиллахад цэгцтэй болгох зарчим дээр тулгуурласан байдаг. Tidyverse-ийн хамгийн түгээмэл хэрэглэгддэг багцуудад dplyr, tidyr, tibble, readr, ggplot2 зэргийг нэрлэж болно.

### Quarto

2022 онд гарсан энэ програм нь R, Python зэрэг программын хэл дээр код, текстийг хослуулан бичиж, улмаар вэб хуудас, тайлан, танилцуулга зэргийг хялбархан бэлдэх боломжийг олгодог програм юм. Тухайлбал, нэг эх бэлдээд түүнийгээ нэгэн зэрэг pdf, word, html, ppt зэрэг олон төрлийн бүтээгдэхүүн болгох боломжийг олгодог. Тайлангаа гаргасны дараа өгөгдөлд өөрчлөлт орлоо гэхэд эх код, текстээ дахин уншуулснаар тайланг автоматаар шинэчлэх боломжийг олгоно. Түүнчлэн өгөгдлөөс хамаарч өөр өөр тайланг нэг ижил код дээр тулгуурлан гаргах боломжийг олгодог. Давтагдах олон тайланг хялбар хийхэд нэн тохиромжтой.

### Эксел

Эксел дээр ажиллаж үзээгүй хүн гэж үгүй биз. Байнга шинэчлэгдэж байдаг тул өгөгдөлтэй ажиллах, хүснэгтэн мэдээлэлтэй ажиллахад улам бүр боловсронгуй болж байгаа. Нэг удаагийн жижиг тооцоолол хийхээс эхлээд санхүүгийн загвар зэргийг хийхэд нэн тохиромжтой.
