---
title: "after_ot"
format: html
---

2010-1-8

Оюутолгойн гэрээг байгуулсны дараа...

Оюутолгойн гэрээг сүр дуулиантай байгуулаад 3 сар орчим болж байна. Энэ мөчөөс ямар үйл явдал өрнөж байна вэ?

Гэрээний дагуу татварын урьдчилгаа төлбөр болгож 100 сая долларыг манай талд шилжүүлсэн билээ. Энэ нь 5.5 хувийн хүүтэй зээл авч байгаа хэлбэр болохыг бонд гаргаснаар нотолсон билээ. Хүү нь боломжийн тул болохгүй зүйл байхгүй л байх. Гэхдээ цаашид стратегийн орд газрыг ашиглахад ийм тохиролцсон зээл биш, гарын үсэг зурсны бонус зэргийг ашиглах боломжтой болов уу.

12 сард Эрдэс баялгийн мэргэжлийн зөвлөлөөс Айвенхоу-ийн ТЭЗҮ-г буцаачихлаа. Сайжруулж ир гээд. Энэ бол төр өөрийн хамтын ажиллагааны уур амьсгалыг бүрдүүлж байгаа халаалт болов уу.

Ашигт малтмалын болон Аж ахуйн нэгжийн татварын тухай хуулиудад Монголын парламент өөрчлөлт орууллаа. Ашигт малтмалын хуулинд байсан татварын заалтуудыг бүгдийг нь хассан. Үнэхээр ч татварын аливаа асуудал татварын хуулиндаа байх нь зохимжтой. Харин аж ахуйн нэгжийн татварын хуулиас "хөрөнгө оруулалтын татварын хөнгөлөлт" хэмээх Оюутолгойд олгосон, ЗГ-ын шийдэх эрхтэй хөнгөлөлтийн заалтыг бүрмөсөн хасав. Ингэснээр тодорхой салбаруудад хөрөнгө оруулалтыг түлхүү дэмжих нэг хэрэгслээсээ ЗГ салж байгаа юм. Гэхдээ энэ хөнгөлөлтийг Оюутолгой эдлэх болсон нь цаашид бас Монгол улсын хувьд сөрөг үр дагавартай байх боломжтой. Үүнийг нэмүү өртгийн албан татвартай холбож дор тайлбарлая.

Нэмүү өртгийн албан татварын тухай хуулинд 2008 оны 7 сард өөрчлөлт оруулж, эцсийн бүтээгдэхүүн л үйлдвэрлээгүй бол экспортод гаргасан бусад ашигт малтмалын бүтээгдэхүүнд НӨАТ-ын буцаан олголт хийхгүй байхаар болсон юм. Уул уурхайн компани их хөрөнгө оруулж байж үйлдвэрлэл явуулдаг ба оруулсан хөрөнгөд нь НӨАТ тооцдог. Харин гаргасан бүтээгдэхүүнээ экспортлосон тохиолдолд тэр орцондоо төлсөн НӨАТ-ыг нь компанид буцаан олгодог жишиг байдаг. Үүнийг НӨАТ-ийг тэг хувиар тогтооно гэж хэлдэг. Харин ингэж тэг хувиар НӨАТ-ыг уул уурхайн бүтээгдэхүүнд тооцсоноор "2005-2008 оны хооронд нийтдээ 242.4 тэрбум төгрөг буцааж олгосон байгаа. Үүний 83.9 хувь буюу 203.4 тэрбум төгрөг нь зөвхөн уул уурхайн салбарт олгогдсон. 2009 онд гэхэд 17.9 тэрбум төгрөгийг энэ салбарт буцааж олгосон байгаа" гэж татварын албаны нэг дарга болох Аюушжав гуай мэдэгдэж байсан. Үүнийг зогсоож, эцсийн бүтээгдэхүүн үйлдвэрлэлийг түлхүү дэмжиж, төсвийн орлогыг богино хугацаанд өсгөх зорилгоор энэ хуулийг гаргасан байх. Бас Бороо голд мэтийн компани их татвараас чөлөөлөгдөөд, дээр нь буцаан олголт авч байгаа нь олон хүний нүдэнд үнэхээр шударга бус харагдаж байсан. Харин энэ бодлого нь буруу юм гэж шүүмжлэгчид олон байна. Мэдээж хамгийн түрүүнд уул уурхайн компани үүнийг эсэргүүцсэн. Харин саяхан Монголын бизнесийн консул гэх байгууллагаас ПрайсУотерХаус Купертэй хамтран татварын хоёр ч семинар хийсэн, тэгээд энэ заалтыг өөрчлөх хэрэгтэй гэсэн захидлыг С. Баярцогт, Д. Зоригт сайд нарт явуулаад, бүр хуульд оруулах өөрчлөлтийн төслийг ч хавсаргажээ. Мөн татварын ихэнх гадны мэрэгжилтэнгүүд ч үүнийг шүүмжлэх байх. НӨАТ орсон үнэтэйгээр эцсийн бүтээгдэхүүнээ борлуулах нь дэлхийн зах зээлд Монголын бүтээгдэхүүн өрсөлдөхөд сөргөөр нөлөөлнө гэж тэд хэлэх байх. Харин Монголын хувьд Оюутолгойн гэрээтэй холбоотойгоор нэг онцгой нөхцөл үүсээд байгаа юм. Үүнийг дор тайлбарлая.

Энэ хууль өөрчлөгдөхөд Оюутолгойн гэрээ хэлэлцээ ид шийдэрлэх шатандаа явж байсан. Ийм хууль гараад ирэнгүүт Айвенхоугийнхан тэгвэл Хөрөнгө оруулалтын татварын хөнгөлөлтийг бидэнд өг гэж наймаалцсан. Уг нь тухайн үед уул уурхайн салбарт энэ хөнгөлөлтийг эдлүүлдэггүй байсан. Гэхдээ ямар салбарт энэ хөнгөлөлтийг эдлүүлэхийг Засгийн газар шийддэг болохлээр гэрээг нэн хурдхан батлуулахыг эрмэлзэж байгаа нь харагдаж байсан Засгийн газрын хувьд үүнийг шууд зөвшөөрсөн. Ингэснээр НӨАТ-ын буцаан олголтыг авахаа больсон шийдвэр Айвенхоуд нөлөөлөхөөргүй болсон. Харин ч тэдэнд ашигтайгаар эргэсэн гэж хэлж болно. Зарим нэгэн тооцоогоор НӨАТ-ын буцаан олголт 400 орчим сая доллар байх дүн гарсан байдаг. Харин Хөрөнгө оруулалтын хөнгөлөлт ойролцоогоор ийм дүнтэй, бүр үүнээс давсан дүнтэй байх ч тооцоо бий. Гэхдээ хамгийн гол нь хөрөнгө оруулалтын гэрээнд татварын орчны тогтворжилт нь нэг урсгалтай тогтворжилт юм. Өөрөөр хэлбэл, татварын хууль тогтоомж компанид таатай байдлаар өөрчлөгдвөл өөрчлөлт тухайн компанид үйлчилнэ, харин компанид ашиггүй байдлаар өөрчлөгдвөл уг гэрээний нөхцөл өөрчлөгдөхгүй. Өөрөөр хэлбэл, НӨАТ-ын буцаан олголтыг буцаагаад өгүүлдэг болгочихвол Айвенхоу хөрөнгө оруулалтын татварын хөнгөлөлтийг эдлээд зогсохгүй, НӨАТ-ын буцаан олголтыг ч эргүүлэн авах болно. Ингэснээр үндсэндээ наад зах нь 400 сая доллар Засгийн газарт бус, компанид нэмэлт хэлбэрээр очих юм. Тиймээс ч Айвенхоугийн хувьд энэ хууль өөрчлөгдөх нь нэн ашигтай. Монголын бизнесийн зөвлөл олон гишүүнтэй байх, гэхдээ эрх ашиг нь хамгийн их хөндөгдөж байгаа гишүүн нь Айвенхоу л байх. Яваандаа энэ хууль өөрчлөгдөх магадлалтайг Айвенхоугийнхан тухайн үед тооцож л байсан байх. Удахгүй төсвийн ихээхэн хувийг бүрдүүлээд эхлэхээр тэдний энэ хүслээ хэрэгжүүлэх нөлөө ч нэмэгдэх биз...

Өөр нэг болж байгаа үйл явдал бол Айвенхоу Сити зэрэг зөвлөх компаниудыг хөлслөх болжээ. Ямар зорилгоор? Компаниа ашигтайгаар зарах гэж үү? Магадгүй л юм.

Засгийн газрын зүгээс хувьчлах объектуудын жагсаалтыг УИХ-д санал болгосон бололтой. Түүнд Оюутолгойн нэр цохиж явна гэнэ. Зарчмын хувьд Оюутолгойн 34 хувийг хувьчилж болноо. Гэхдээ үүнд хоёр асуулт урган гарч байгаа. Хувьчлах байсан юм бол 34 хувийг авахын тулд яах гэж зөндөө олон буулт гэрээг байгуулахад хийсэн юм бэ? Бас гэрээг байгуулахад төрийн компани байнаа гээд хатуу заалт оруулсан байгааг өөрчлөх болох уу? Нөгөө нэг асуулт нь мэдээж хэн, ямар үнээр хувьчилж авах юм бэ? Хувьчлалыг, дахин хуваарилалтыг маш сайн хийдгийг бид бүгд дутахгүй сайн мэднэ шүү дээ. 20 жилийн түүх байна.

Үргэжлүүлнээ...