---
title: "boroo_gold"
format: html
---

2009-3-4

Бороо Голд, Киргиз Монголын алтыг ухсан ижил түүх

Бороо Голд компанид Монголчууд ам муутай байдаг. Үнэхээр ч 40 тонн орчим алтыг нь авчихаад татвар бага төлсөн гадны компанийг Монголчууд сайн хэлэхгүй. Харин компани бол хэзээ ч хууль зөрчөөгүй. Өөр нэг хүлээн зөвшөөрөх зүйл бол Монголд ажиллаж байгаа бусад алтны компаниас хавьгүй дээр технологи ашигладаг, ажилчдынхаа аюулгүй байдлыг хангадаг, үндсэн орд ашигласан зэргийг дурьдахгүй байхын аргагүй.

Харин Киргиз найз нартайгаа хуучлах боломж сүүлийн хэдэн жил надад нилээд хэд тохиосон юм. Нэгэнт тэдний Кумтор гэгч томоохон алтны ордыг ижилхэн компани олборлодог тул яах аргагүй Бороогийн тухай, Бороогийн толгой компани болох Сентерра Голд-ын тухай яриа өрнөнө. Зарим нэгэн сонирхолтой мэдээг та бүхэнтэй хуваалцах гэсэн юм.

Кумторыг анх Зөвлөлтийн үед илрүүлэн, алтны нөөцийг нь 850 орчим тонн гэж тогтоожээ. Харин Сентерра Голд Кумторыг ашиглаж эхлэхдээ 850 тонн байхгүй, нөөцийг нь 139 орчим тонн л байна гэж, Киргизийн Засгийн газартай гэрээ байгуулжээ. Ингэхдээ мөн л татварын хөнгөлөлтийг эхний хэдэн жил эдлэх болов. Харин төлөвлөж байсан тоо хэмжээнээсээ хавьгүй илүү алтыг цөөн жилийн дотор олборлочихов. Татвар төлөхгүй хугацаандаа гэсэн үг. Бидний мэдэх түүх байгаа биз?

Киргизүүд үүнийг зүгээр хараад сууж чадсангүй, гэрээгээ шинэчилж, Сентерра-д хувь эзэмшигчээр оролцох болов. Харин Сентерра нь Бороогийн хувьцааг эзэмшигч. Өөрөөр хэлбэл канадчуудаас гадна киргизүүд манай Бороогийн алтнаас хувь хүртэж байхад, бид харин саяхнаас л бага зэрэг татвар авахаар гэрээг өөрчилж чадсан.

Өөр нэг түүх яах аргагүй анхаарал татна. Саяхан нөгөө 139 тонн алтаа Сентерра Кумтор дээр олборлоод дуусчихжээ. Тэгээд хуучин гэрээгээрээ (мэдээж татвар бага төлөхүйц) үргэлжлүүлээд алт олборлоно гэсэн гэнэ. Нөгөө 139 тонн л байсан гээд байсан нь худлаа болж таарлаа. Мэдээж компани бол бид нэмэлт хайгуул хийсэн л гэж байгаа байх. Зөвлөлтийн үед тогтоосон 850 тонн нь бодитой тоо байсан бололтой. Бас л бидний мэдэх түүх байгаа биз? Гацууртыг хуучин Бороогийн гэрээгээрээ ашиглах сонирхол Бороо голд-д байгаа нь мэдээж. Элдэв "гэнэтийн" татвар төлөхгүй.

Бас нэгэн "сонин" зүйл бол нутгийн иргэд гээд хэдэн нөхдүүд үе үе ажилд нь саад болно. Кумтор нь өндөр уулан дээр байрладаг болохлээр очдог зам нь ганцхан. Жаахан цианид асгасан чинь иргэд нь нөгөө замыг нь хаагаад зогсчихсон. Бүх ажил зогссон. Бөөн юм болж замаа нээсэн. Түүнээс хойш жаахан юм болохлээр л зам хаачих гээд байдаг. За тэгээд тэр цианид асгаснаас болоод бөөн мөнгө нэхсэн хүмүүс. Харин саяхан нутгийн иргэд болох нийт 2000 өрхөд 3 сая доллар хувааж өгсөн гэнэ. Нэг өрхөд 900 орчим доллар ногдсон гэнэ. Мэдээж компани албан ёсоор өөрсдийн бурууг хэзээ ч хүлээн зөвшөөрөөгүй. Харин албан бусаар бол асуудлыг ийнхүү намжаах биз. Манайд сумын хөгжлийн санд хэдэн төгрөг өгдөгтэй төстэй сонсогдохгүй байна уу?

Киргиз найз нартайгаа иймэрхүү л зүйл ярьж сууна. Бодох юм их л байх шиг.