---
title: "cash_to_citzens_ot"
format: html
---
2009-4-6

1.5 сая төгрөг иргэн бүрт өгөх, Оюутолгойн гэрээг зурах хоёр ижил үү

Оюутолгойн гэрээг УИХ-ын хаврын чуулганаар хэлэлцэх нь. Харин саяхан зад шүүмжилж байсан гэрээний төслөө ер нь тэр чигээр нь баталчих нь зөв гэх улс төрчдийн тоо өдөр ирэх тусам нэмэгдсэн харагдана. Хамгийн сонирхолтой нь энэ гэрээг хэлэлцэхтэй хамт иргэн бүрт 1.5 сая төгрөг өгөх асуудлыг УИХ-аар хэлэлцэхээр болжээ. Ингэж энэ гэрээг батлах асуудлыг иргэдэд мөнгө өгөх асуудалтай барьцаалж байгаа нь ямар учиртай вэ?

1.5 сая төгрөг өгөхийг МАХН сонгуулийн үеэр амалсан. Амлалтаа эс биелүүлвээс дараагийн сонгуулиар олон саналаа алдах магадлалтай. Харин энэ мөнгийг олгочихвол дараа дараачийн сонгуульд ялалт байгуулах магадлал нэмэгдэнэ. Энэ бол хэнд ч ойлгомжтой. Харин энэ асуудлыг шийдэхийн тулд Оюутолгойн гэрээний төслийг их шүүмжлэгдсэн хувилбараар нь батлах нь энгийн иргэдэд яав ч ашигтай биш. Энэ гэрээг байгуулж, хөрөнгө оруулагчийг шахаж байж ирээдүйд авах мөнгөө өндөр үнэ төлж байж өнөөдөр авах боломжтой. Цаашид Тавантолгой зэрэг бусад томоохон ордуудыг ч ийм байдлаар гэрээлж, ашиглалтанд оруулж болно. Ингэснээр бид үнэндээ ирээдүйгээсээ хумсалж, өнөөдөр тэр 1.5 саяыг л авахыг тэмүүлж байгаа хэрэг. Бидэнд мэдээж мөнгө хэрэгтэй, гэхдээ их мөнгө ямар нэгэн бүтээлч үйл ажиллагаатай уялдахгүй бол эргээд бидний аж амьдралыг дээшлүүлэх нь эргэлзээтэй. Дээрээс нь энэ мөнгийг бэлэн мөнгөөр, тэр тусмаа энэ сонгуулийн дөрвөн жилд өгөх нь үнэндээ боломжгүй гэдгийг олон эдийн засагчид хэлж байгаа, энгийн иргэн тооны машин аваад үзсэн ч болно.

Тэгэхээр ингэж энэ хоёр асуудлыг хольж, тийм ч сайн биш гэрээг батлуулах гээд байгаа нь хэний ашиг сонирхолд нийцэх вэ?