---
title: "Тойргийн мөнгийг яах бол?"
format: html
---
2010-4-7

Тухайн үед гишүүн тус бүрийн 250 сая төгрөг болсон тойргийн мөнгийг үндсэн хууль зөрчсөн гээд 2008 онд цэийн шийд гарсан ч УИХ тоогоогүй, 2009 онд 500 сая, 2010 онд нэгтэрбум болсон билээ. УИХ энэ мөнгөнөөсөө татгалзах уу, эсвэл хэт ил хийж байснаа далдалж, энгийн хүн тойргийн мөнгө гэж байгааг мэдэхгүй түвшинд нуух уу гэдгийг энэ хаврын чуулганаас харах үлдэж байна.

Ийм мөнгө дэлхийн бусад хэд хэдэн оронд байдаг юм байна. Пакистанд анх 1985 онд гарсан гэж ярих юм. Мөн Африкийн хэд хэдэн оронд, тухайлбал Кени зэрэгт ийм мөнгө байдаг юм байна. Дэмжигчид ч нилээдгүй байдаг бололтой. Харин сөрөг тал нь ялангуяа манайх шиг ил тод байдал муу, хариуцлага тооцолт гэж байдаггүй нийгэмд илүү их юм болов уу. Гол нь төсвийн төвлөрлийг сааруулна гэж ярьдаг ч орон нутгийн удирдлагад огт итгэл үзүүлэхгүй байгаа нь энэ мөнгөнөөс харагдаж байна. Мөн засаглалын хуваарь тал дээр ерөнхийлөгчөөс авахуулаад олон хүн их сөрөг үр дагавартайг нь хэлсэнийг санах хэрэгтэй.