---
title: "human_devt"
format: html
---
200912-21
Хүний хөгжил сан

Монголд олон сан байдаг. Олон сайхан нэртэй. Ихэнхийнх нь үйл ажиллагааны үр дүн тодорхой биш. Харин саяхан нэг том сан байгуулахаар болжээ. Хүний хөгжил сан. Тусгай хуулиар зохицуулагдах цөөхөн сангийн нэг. Сонирхоод хуулийг нь үзлээ. Хуульч биш болохоор ойлгох юм алга. Гэхдээ хуульч биш хүний нүдэнд тусах зарим нэгэн зүйл байнаа.

Үндсэн санаа нь уул уурхайн баялгийг ард түмэндээ тэгш хүргэх. Энэ тухай хоёр нам нэг нь хишиг, нөгөө нь хувь гээд сонгуулийн үеэр амлачихсан. Харин хоёр нам зөвшилцөлд хүрч, хүний хөгжлийн нэртэй байхаар тогтжээ. Харин хуулинд хишиг, хувь гэх үгийг зэрэгцүүлэн хэрэглэжээ. Энэ хууль хүчинтэй байхад энэ хоёр намыг би л лав мартахгүй болжээ. За тэр ч яахав.

Хууль сангийн үйл ажиллагааг зохицуулах зорилготой гэж ойлголоо. Гэтэл сангийн удирдлагын тухай ганцхан өгүүлбэртэй. Удирдлагыг Сангийн яам хэрэгжүүлнээ гээд. Өөрөөр хэлбэл, энэ яаманд мөнгийг хэрхэн зарцуулах талаар хязгааргүй шахуу эрх мэдэл өгчээ. Харин санд орлого төвлөрүүлэх үүрэгтэй нэг компани байх юм байна. Тэр компанийн удирдлага зохион байгуулалтын талаар тус компанид шал хамаагүй энэ хуулинд их л нарийн зааж өгсөн байх юм. Яагаад? Бүү мэд. Өөрсдийнхөө эрх зүйн орчны баталгааг өөр хуулиар далимдуулан гаргаж авч байгаа юм байлгүй дээ. За тэгээд тэр компанид нь баахан л төрийн төлөөлөгчид орох бололтой, иргэний нийгмийн хяналт байвал уг нь зүгээрсэн.

Санд стратегийн ордуудад төр хувь эзэмшиж байгаа бол тэр хувьд ногдох ногдол ашиг, мөн уул уурхайн үйл ажиллагааны нөөц ашигласны төлбөрийг хуримтлуулахаар тохирчээ. Яагаад зөвхөн стратегийн ордуудын гэж? Бусад уул уурхайн баялаг ард түмний өмч биш гэж үү? Ингэж зааглах эрх зүйн үндэс бий юу? За хуульчид хариулна биз дээ.

Энэ мэтээр энэ богинохон хуулинд зарчмын гэмээр олон л асуудал байх шиг байна.

Гол нь бүх удирдлага Сангийн яамны мэдлээр явах тул алт дилерийн хэрэг гэдэг шиг олонд очих учиртай мөнгийг арвижуулж байна гээд хэдэн ашиггүй хувьцаанд тавиад туучих бий дээ.