---
title: "mmj_interview"
format: html
---

2011-4-13

Гэрээг монголын талд ашигтайгаар өөрчлөхөд хариуд нь заавал нэг зүйл тулгах байдал ажиглагдах юм - Mongolian Mining Journal

Оюутолгойн Хувь нийлүүлэгчдийн гэрээнд нэмэлт өөрчлөлт оруулахаар хөрөнгө оруулагч талтай харилцан тохиролцоонд хүрснээ Монгол улсын Засгийн газар албан ёсоор мэдэгдлээ. Гэрээнд орсон өөрчлөлтийг судлаачид хэрхэн хүлээж авч байгаа бол? Энэ талаар “Нээлттэй нийгэм форум”-ын менежер, судлаач Н.Дорждарийн байр суурийг сонирхсон юм. “Нээлттэй нийгэм форум” Оюутолгойн гэрээг нэлээд ултай судалж, дүн шинжилгээ хийж байсныг уншигчид санаж байгаа биз ээ.

Оюутолгойн Хувь нийлүүлэгчдийн гэрээнд хэд хэдэн асуудлаар нэмэлт өөрчлөлт оруулахаар болжээ. Энэхүү өөрчлөлтийн талаар байр суурийг тань сонирхмоор байна?

Оюутолгойтой холбоотой гурван ч гэрээ байдаг. Хөрөнгө оруулалтын, Хувь нийлүүлэгчдийн, Урьдчилгаа төлбөр буюу Засгийн газрын үнэт цаасны гэсэн гурван гэрээ. Сүүлийнх нь үндсэндээ зээлийн гэрээ. Би хувьдаа Хувь нийлүүлэгчдийн гэрээнд өөрчлөлт орж байгаа юм байна гэж ойлгож байгаа. Энэ гэрээний монгол хувилбар нь нууц байна гэсэн асуудлыг УИХ-ын зарим гишүүд хөндөн тавьж байсан. Тэгэхээр гэрээнд өөрчлөлт үнэхээр орсон, үгүйг одоохондоо хэлж мэдэхгүй юм. Засгийн газрын мэдээлснээр тодорхой өөрчлөлт оруулахаар хөрөнгө оруулагчидтай харилцан тохиролцсон гэсэн хэмжээнд л мэдээлэлтэй байна. Энд хоёр ерөнхий зүйлийг онцолж хэлье. Хувь нийлүүлэгчдийн гэрээ яагаад нууц байгаа юм бэ гэдэг асуудал дахин босч ирж байна. Газрын баялаг бол ард түмний өмч. Ард түмний өмчийг ард түмний нэрийн өмнөөс төр засаг захиран зарцуулж байгаа. Эдийн засгийн утгаараа ч тэр, нийгмийн агуулгаараа ч тэр Монгол улсын хөгжилд маш чухал ач холбогдолтой, хуулийнхны ярьдгаар материаллаг ийм зүйлсийг олон нийтэд ил танилцуулах зайлшгүй шаардлагатай. Хөрөнгө оруулалтын гэрээ, Хувь нийлүүлэгчдийн гэрээг хамтад нь авч үзэж байж, энэ гэрээ Монгол улсад ашигтай болж уу, үгүй юү гэдгийг үнэлэх боломж олдоно. Нэг гэрээ нь нууц гээд нийтэд ил биш болохоор ямар нөхцөлөөр гэрээ байгуулсан нь үндсэндээ ойлгомжгүй. Хөрөнгө оруулалтын гэрээ бүх асуудлыг ил болгож чадахгүй. Тиймээс эхний ээлжинд Хувь нийлүүлэгчдийн гэрээг ил болгох хэрэгтэй. Бусад улс орны чиг хандлага ч гэсэн гэрээ хэлэлцээрийг ил болгоход чиглэж байна. Нууцлахын тухайд бол гэрээний нарийн зүйл заалт, бизнесийн өртөг зардал ямар байгааг өрсөлдөгчид нь мэдчихвэл компанийн өрсөлдөх чадварт сөргөөр нөлөөлнө гэж зарим хүмүүс тайлбарладаг л даа. Гэвч хамгийн инээдтэй нь Хувь нийлүүлэгчдийн энэ гэрээ англиар вэб сайт дээр ил байгаа. Түүнчлэн гэрээнүүдийг зардаг компаниуд байдаг. Өндөр үнээр зардаг болохоор компаниуд л авах бололцоотой. Тэгэхээр өрсөлдөгч компаниуд бол тэр гэрээг аль хэдийнэ олоод авчихсан байгаа. Харин баялгийн жинхэнэ эзэд ард түмэн гэрээг үзэх эрхгүй байж болохгүй биз дээ. Хоёрдугаарт, Оюутолгойн гэрээг байгуулаад удаагүй байна. Хүчин төгөлдөр болоод жил ч болоогүй байхад өөрчлөлт оруулж байгаа нь анхнаасаа гэрээг байгуулахдаа асуудлыг бүрэн дүүрэн авч үзээгүй, илүү нөхцөл шаардах бололцоо байсаар байтал түүнийг ашиглаагүй дүр зургийг л харуулж байна. Нэлээд яаруу байдлаар улс төрийн шийдэл нь гараад гэрээ байгуулсан дүр төрх эхнээсээ харагдаж байна шүү дээ.

Санхүүжилт болон зээлийн хувь хэмжээний өөрчлөлт анхаарал татаж байна. Үнэхээр нааштай сайн өөрчлөлт хийгдэж чадсан уу?

Зургаа долоон асуудлаар өөрчлөлт оруулна гэж Засгийн газар мэдэгдэж байна лээ. Мэдээж хэрэг, санхүүжилт болон зээлийн хувь хэмжээ анхаарал татсан асуудал мөн. Анх байгуулсан гэрээгээр Монгол улс “Оюутолгой” компанийн 34 хувийн хувьцааг “Айвенхоу Майнз” компаниас зээл аваад төлчихөж байгаа. Тэр зээлийн хүү 9,9 хувь гэдэг нь бодит хүү. Бодит хүү бол инфляцийг тооцоогүй хүү. Нэрлэсэн хүү гэвэл Америкийн инфляци ямар байхаас хамаараад 13 хувь орчим болж байгаа юм. АНУ-ын инфляци олон жилийн дундаж нь 3 орчим хувь байдаг. Бид анхнаас нь л маш өндөр хувь хэмжээтэй зээл авч байгааг нь сануулж байсан. Гэрээ байгуулж байх үед хувийн компаниуд үүнээс хамаагүй бага хэмжээний хүүтэй зээл авч байсан. Энэ чинь бүхэл бүтэн улс шүү дээ. Адаглаад хувийн компанийн авч байгаа үнээр зээл авах бололцоотой гэдэг асуудлыг тавьж байсан. Үүнийг ойлгоод өөрчилж байгаа нь сайн хэрэг. Одоогийн шинэ хувилбараар Лондонгийн банк хоорондох зээлийн хүү буюу LIBOR нэмэх нь 6,5 хувь гэсэн байна. Банк хоорондын зээлийн хүү гэдэг нь хоёр банк хоорондоо итгэлцээд бие биедээ зээл өгөхдөө ашиглаж байгаа үнийн түвшин. Нэг банк Монгол улсын Засгийн газартай итгэлцээд зээл өглөө гэхэд яагаад тэр LIBOR хүүгээр байж болохгүй гэж. Мэдээж зээл авахтай холбоотой янз бүрийн өртөг зардал, эрсдэл зэргийг бодоод бага зэргийн хүү нэмж болно л доо. Тэгэхдээ 6,5 гэдэг бас л өндөр хувь. Оюутолгойн гэрээг анх яригдах үед LIBOR нэмэх нь 3,3 хувь гэж байсан. Гэтэл одоо 6,5 болчихлоо. Уул нь Монгол улсын зээлжих эрх тэр үеийг бодвол дээшилчихсэн байгаа. Дээрээс нь гэрээ яг батлагдах үед хямрал болж байсан. Одоо бол зээлүүлье гэсэн сул хөрөнгө дэлхийн зах зээл дээр маш их байна. Үүнийг хайж эрэлхийлэх нь л чухал байгаа юм. Өөр нэг техникийн шинж чанартай зүйл гэвэл Америкийн инфляци хасах дүнтэй гарч болдог тоо. Хямралын дараа тийм байсан шүү дээ. Тэнд инфляци буюу үнийн өсөлт биш бууралт ажиглагдаж байсан. Тэгвэл 9,9 хувиасаа хасагдаад явна гэсэн үг. LIBOR одоо хамгийн доод цэгтээ байгаа. Ахиад доошилно гэсэн ойлголт байхгүй. 6,5 гэдэг нь LIBOR 0 байхад байх хувь. Дээшлээд явбал нэмэгдэнэ. Бас л 3-4 хувьд хүрэх магадлалтай. Тэгэх юм бол эргээд л 10 хувийн зээл болчихож байгаа юм. Урт хугацаанд харах юм бол бид LIBOR-ийг хамгийн бага байхад нь энэ хэлэлцээрийг хийж байна. Түүн дээр 6,5 хувийг нэмж байна гэдэг нь 6,5 хувь дээр нэмэх нь 3-4 хувь болох асуудал үүсч байна гэсэн үг шүү дээ. Ийм тал байгаа ч 9,9 хувь дээр нэмэх нь Америкийн инфляци гэдгээс арай дээр л дээ. Тиймээс энэ өөрчлөлтийг хүлээн зөвшөөрч, талархан хүлээж авч байна.

Давуу эрхийн хувьцааг гэрээнээс хасч, зээлийн эрхийн бичгээр санхүүжих болжээ. Давуу эрхийн хувьцааг гэрээнээс хасах хэрэг байсан юм уу?

Бусад өөрчлөлтүүд нь илүү техникийн шинж чанартай байна лээ. Манайх эрхээ баталгаажуулсан зүйлс байсан. Давуу эрхийн хувьцааг ашиглахаа болино гэсэн нэг зүйл байгаа. Эндээс давуу эрхийн хувьцаатай холбоотой 34 хувь хүчин төгөлдөр үү, үгүй юү гэсэн асуудал үүснэ. Ер нь давуу эрхийн хувьцаа нийтлэг байдаг санхүүжилтийн нэг хэлбэр. Байж болох ч хэлбэр. Улс төрийн хувьд хүлээн зөвшөөрөгдөхгүй байх шиг байна. Тэгээд хасч байна гэж би ойлгож байгаа. Анхнаасаа гэрээ нь нууц болохоор олон нийтэд мэдээлэх, тайлагнах тал дээр анхаараагүйгээс болж давуу эрхийн хувьцааг тэр чигээр нь хасах нөхцөл үүсч байх шиг байна. Давуу эрхийн хувьцаа гэдэг нь нэг талаас хувьцаа, нөгөө талаас зээл хэлбэртэй хоёрдмол шинж чанартай хэрэгсэл. Улс төрчид хувьцаа гэсэн тодорхойлолтыг нь авч үзээд асуудалд хандаад байдаг. Нөгөө тал нь зээл гэдэг утгаар хандаад байдаг. Энэ хоёрын хооронд зөрчил үүсээд байгаа юм. Үүнийг олон нийтэд сайн таниулаагүйгээс болж элдэв маргаан ч үүсч байна. Санхүүжилт гуравдагч талын зээл хэлбэрээр явахад болно л доо. Гэхдээ түүний хүүгийн түвшин ямар байх вэ. Түүн дээр бас л тохирсон ёсоор LIBOR нэмэх нь 6,5 хувь гээд хүүгийн түвшин яригдана. Хүүгийн түвшин өөрөө татвар ногдох орлогоос хасагдаж тооцогддог. Тэгэхээр татварын хэмжээг бас л бууруулна. Цаана нь эдийн засгийн тооцоо байгаа байх л гэж найдъя.

Зээлийн хувь хэмжээг өөрчилс­нөөр Монгол улсад 1 тэрбум төгрөгийн ашиг бий болно гэж ярьж байна. Энэ нь хэр бодитой тооцоо вэ?

Тэрбум доллар Монголд илүү орохоор байна гэж Сайд хэлж байна лээ. Бас л мэдээллээ дутуу өгч байгаа болохоор үүн дээр дүгнэлт хийхэд хэцүү. Мэдээж, Засгийн газарт тооцож байгаа загвар байгаа л байх. Тэр загварын дагуу чухам ямар дүн гарч байгаа юм, хэлж мэдэхгүй байна. Бидэнд нэг загвар бий л дээ. Гэхдээ түүнийгээ ашиглаж, энэ талаар тооцоо хийгээгүй байна. Тэрбум доллар гэж өнөөдрийн тэрбум долларыг хэлж байна уу, эсвэл 30 жилийн дараах тэрбум долларыг ярьж байна уу гэдэг нь ойлгогдохгүй байна. Эндээс улс төрчид маань салаа утгатай зүйл мэдэгдчихдэг. Түүнийгээ дараа нь яаж л бол яаж тайлбарладаг байдал харагдаж байгаа юм. Тэрбум доллар өнөөдрийнхөөр бол маш их мөнгө. 30 жилийн дараагаар бол үндсэндээ өнөөдрийн 300 сая доллар ч хүрэхгүй л мөнгө. Цаг хугацаа үнэ цэнтэй гэдгийг бүгд мэднэ. Иймэрхүү салаа утгатай мэдэгдлүүдийг хиймээргүй байна. Хийж байгаа бол түүнийгээ маш тодорхой хэлэх хэрэгтэй. Нөгөө талаас тэрбум долларыг зөвхөн хүүн дээр алдах гэж байсан бол энэ гэрээний чанарт эргээд эргэлзээ төрөхөөр байна. Гэрээнд нэмэлт өөрчлөлт оруула­хаар нааштай тохиролцоонуудыг хийж байгаа нь сайн хэрэг. Цаашид ч бас өөрчлөлт хийгдэж, илүү сайжраад явах ёстой байх.

Таны бодлоор цаашид Оюутолгойн гэрээнд зайлшгүй өөрчлөх ёстой ямар зохицуулалтууд байна вэ?

Урт хугацаатай байгуулсан гэрээнд өөрчлөлт ороод явдаг нь байдаг л практик. Бүгдийг урьдчилан харж, гэрээг төгс байгуулчихна гэж байхгүй. Тодорхой хугацаанд хоёр талаас гэрээгээ эргэн харж, шинэчлэх ажлыг байнга хийх ёстой. Оюутолгойн гэрээнд өөрчлөлт оруулах зүйл нэлээд байгаа. Хэд хэдэн өөрчлөлтийг зайлшгүй оруулах ёстой. Гэрээг байн байн өөрчлөөд байх нь хөрөнгө оруулагчдад мэдээж түвэгтэй. Гэхдээ гэрээ аль ч талдаа боломжийн байхгүй бол урт хугацаанд тогтвортой байх магадлал муу шүү дээ. Хэн хэндээ ашигтай, хэн хэнийгээ бодолцсон, аль болох хуулийн дагуу хийгдсэн байвал хөрөнгө оруулагч талдаа ч хэрэгтэй. Нэг зүйл ажиглагддаг нь ямар нэг байдлаар гэрээг өөрчиллөө гэхэд, магадгүй Монголын талд илүү ашигтайгаар өөрчлөхөд хариуд нь заавал нэг юм нэхэх гээд байдаг. Тэр нь Монгол улсад үйлчилж байгаа хууль тогтоомжийг өөрчлөхөд хүртэл хүрдэг. Ялангуяа гэрээг байгуулж байх явцад энэ байдал илүүтэй ажиглагдсан. Энэ гэрээг байгуулахад Монгол улс дөрвөн хуулиа өөрчлөхөд хүрсэн. Ингэж жижиг улсад хөрөнгө оруулахдаа хууль тогтоомжоо өөрчил гэсэн шаардлага тавих нь зүй ёсны хэрэг үү, үгүй юү гэдэг асуудал ч эндээс гарч байгаа юм. Манай улсын хууль тогтоомж боловсронгуй биш байж болно. Хуулийг өөрчилж болно. Гэхдээ нэг компанийн төлөө хуулийг байн байн ингэж өөрчлөөд байж болох уу гэдэг асуудал гарна биз дээ. Нэн тэргүүнд өөрчлөх зүйлийн тухайд бас л санхүүтэй холбоотой зүйл хэлмээр байна. Хувь нийлүүлэгчдийн гэрээнд менежментийн төлбөр гэж бий. Менежментийн төлбөрт үйлдвэрлэлийн үйл ажиллагаа эхэлтэл бүх зардлын 3 хувь, бүтээгдэхүүний үйлдвэрлэл явж эхэлснээс хойш бүх зардлын 6 хувийг “Айвенхоу майнз” компани авахаар байгаа. 5 тэрбумын хөрөнгө оруулалтын зардал орууллаа гэхэд бүтээгдэхүүн үйлдвэрлэж эхлэхээс өмнө 3 хувь нь эргээд менежментийн төлбөр гээд гадагшаа гарчихаж байгаа юм. Менежментийн хөлс төлбөр гэж байлгүй яахав. Монгол улс энэ төслийг бие даагаад удирдлагыг хэрэгжүүлчих бололцоо хараахан байхгүй гэж үзэж байгаа бол гаднаас менежмент авч болно. Асуудал нь төлбөрийн хувь хэмжээндээ байгаа юм. Харьцангуй өндөр хувь хэмжээ энд тавигдсан. “Рио Тинто” гэдэг компани хаанахын ямар улсад 3 хувь, 6 хувийн менежментийн төлбөр авдаг юм бэ гэдгийг энэ чиглэлийн маш олон хүмүүсээс асууж сураглаж, сонирхож үзлээ. Тийм газар байдаггүй юм байна. Монгол улсад үйлдвэрлэл явж эхэлснээс хойш бүх зардлын 6 хувийг авна гэдэг маш өндөр төлбөр. Нөгөө талаасаа менежментийн төлбөр гэдэг нь тодорхой үйлчилгээ үзүүлсний хөлс байх ёстой. Өөрөөр хэлбэл, бидний чаддаггүй, мэддэггүй ямар нэг үйлчилгээг үзүүлсний төлөө авч байгаа хөлс шүү дээ. Хамгийн гол нь энэ гэрээнд менежментийн төлбөрийг ямар нэгэн үйлчилгээтэй холбож өгөөгүй. Ерөнхий томъёолчихсон. Заримдаа өдөр тутмын сонинуудын бараг ¼ хувьд нь Оюутолгойн зар мэдээлэл явж байгааг та бүхэн ажиглаж байгаа байх. Энэ чинь компанийн үйл ажиллагааны зардал гээд л бүртгэгдэнэ. Түүний 3 хувийг Австралид сууж байгаа ч юм уу, Лондонд сууж байгаа компани менежментийн үйлчилгээ үзүүлсний хөлс гээд авчихаж байна. Сонинд зар тавих нь монголчуудын чадахгүй зүйл мөн үү гээд наад захын энгийн асуудал байна. Эсвэл мэргэжлийн боловсон хүчин бэлтгэнэ гээд Оюутолгойн зардлаар маш олон хүнийг ТМС-д сургаж байна. Тэр зардлын 3 хувийг, магадгүй үйлдвэрлэл эхэлснээс хойш 6 хувийг Англид сууж байгаа компани авчихна. Сургалтын тэтгэлэг өгөхийг монголчууд чадахгүй гэж үү. Харин далд уурхайд блокчлон олборлох арга, технологийг Монголд эзэмшээгүй учраас үйлчилгээний 6 хувийг нь төлөх боломжийн байж болно. Менежментийн төлбөр ямар нэг үзүүлсэн үйлчилгээний хөлс байх ёстойг гэрээнд огт тусгаж өгөөгүй. Үйлчилгээ үзүүлсэн ч байсан, үзүүлээгүй ч байсан, монголчуудын чаддаг үйлчилгээг ч үзүүлсэн, чаддаггүй үйлчилгээг ч үзүүлсэн маш өндөр хөлс авахаар заачихсан байгаа. Үүнийг зайлшгүй эргэж харах ёстой. Үүнтэй холбоотой, бас тусдаа ч авч үзэж болохоор нэг асуудал бий. Тэр нь суутгал татвар. Тухайлбал, энэ жил тэрбум доллараар хөрөнгө оруулалт хийхэд менежментийн хөлс гээд 3 хувийг авчихна. Тэрбум долларын 3 хувь нь 3 сая доллар. Энэ бол тэр компанийн Монголоос олж байгаа орлого шүү дээ. Монгол улс түүнээс нь татвар авах эрхтэй байх ёстой. Энэ бол хаана ч үйлчилдэг хууль тогтоомж. Харамсалтай нь давхар татварын гэрээгээр наймаалцах явдал олон улсын томоохон компаниудад байдаг л даа. Монгол улсын хуулиар суутгал татвар гээд 3 сая доллараас 20 хувийг авах ёстой. Гэтэл Канадтай байгуулсан давхар татварын гэрээнд 5 хувиар авахаар заачихсан байдаг. Нидерландтай байгуулсан гэрээгээр огт татвар авахгүй гээд заачихсан байх жишээтэй. Оюутолгойн Хөрөнгө оруулалтын гэрээг Канад дахь “Айвенхоу Майнз”, Лондонд бүртгэлтэй “Рио Тинто” хоёртой байгуулсан. Тэгсэн мөртлөө Хувь нийлүүлэгчдийн гэрээг яагаад ч юм “Оюутолгой Нидерланд” гэдэг Нидерландад бүртгэлтэй компанитай байгуулчихсан байдаг. Тэгээд Хувь нийлүүлэгчдийн гэрээгээр суутгал татварыг авахгүй нөхцөл үүсчихэж байгаа юм. Энэ нь маш их хэмжээний мөнгөний асуудал учраас ярьж байгаа юм. Ялангуяа Монгол улс “Оюутолгой” гэдэг компанид 34 хувийг эзэмшихдээ мөнгө төлж, өөрсдөө хөрөнгө оруулж байгаа. Хэрвээ бид 20 хувийн суутгал татвараа авах юм бол 20 хувийг тэр компанид эзэмшиж байгаагаас ялгаагүй. Гэхдээ мөнгөө төлөхгүй эзэмшинэ гэсэн үг. Эдийн засгийн агуулга нь энэ. Жишээлбэл, бид хувьцаагаа үнэгүй авах ёстой гэж зарим хүмүүс ярьдаг. 34 хувийг үнэгүй авах, суутгал татвар нь 34 хувь байх хоёрын эдийн засгийн үр дүн яг тэнцэнэ. Тиймээс манай улс давхар татварын гэрээнүүдээ цэгцлэх ёстой. Өөрчлөх ч боломжтой. Гэрээ гэдэг мөнхийн зүйл биш. Ялангуяа хөгжингүй улсад, тухайлбал Нидерландад хэчнээн монгол хүн очиж хөрөнгө оруулах билээ гэдгийг бодох ёстой. Ямар улстай, ямар давхар татварын гэрээ байгуулах вэ гэдгээ эргэн харж, энэ ажлыг яаралтай хийх ёстой юм. Тэгээд ч энэ гэрээн дээр “Оюутолгой” Нидерландын компани гэдгийг хүлээн зөвшөөрөх ёстой юү, үгүй юү гэдгээ ч тодорхой хэлж өгч болно шүү дээ. Мөн өсөн нэмэгдэх роялти байна. Энэ бол хөрөнгө оруулалтын гэрээний асуудал л даа. Монголд хууль нь батлагдчихсан ч “Оюутолгой” компанид үйлчлэхгүй байгаа. Би хувьдаа энэ татварыг “Оюутолгой” компани төлөх ёстой гэж боддог. “Хэт өндөр” ашгийн талаарх рент гэж ойлголт бий. Хөрөнгө оруулагчаас үл хамаарах, хөрөнгө оруулагчийн шийдвэрт үл нөлөөлөх тийм өндөр ашигтай холбоотой зүйл. “Оюутолгой” компани 5 тэрбум доллар оруулаад 20 тэрбумын ашиг олно гэж тооцоолж байтал 40 тэрбумыг олчихлоо гэж бодъё. Тэр нь дэлхийн зах зээл дэх бүтээгдэхүүний үнээс хамаарчээ. Энэ нь мэдээж, компанидаа сайн хэрэг. Тэр нэмэлт 20 тэрбумын 50 хувийг Засгийн газар авчихлаа гэж бодъё. Тэгвэл 30 тэрбумын ашигтай, өөрөөр хэлбэл, хүлээгдээгүй 10 тэрбумын ашиг орж ирж байна гэсэн үг. Эсвэл 20 тэрбумыг тэр чигээр нь авчихлаа ч гэсэн цаана нь тооцоолж байсан 20 тэрбумын ашиг байж л байгаа. Тэр рэнтээс татвар авахад компани хөрөнгө оруулалтын шийдвэрээ өөрчлөхгүй байх бололцоотой. Мэдээж, төлөвлөснөөс давах ашгийг бүгдийг авах нь компанидаа хүлээн зөвшөөрөх аргагүй зүйл байж болно. Гэхдээ тэндээс баялгийн эзэн болсон ард түмнийг төлөөлж байгаа төр ямар нэгэн байдлаар авах нь зүйтэй юү гэвэл зүйтэй. Яагаад гэвэл үнэ байнга хэлбэлздэг. Ялангуяа үнэ өсөхөд компани алдагдалд орохгүй. Компанийн төсөөлж байгаа орлого нь үнэ буурах магадлалыг тооцчихсон ашиг байдаг. Нөгөө талаас Оюутолгойн гэрээг байгуулахад Гэнэтийн ашгийн татвар гэж байсан. Зөвхөн Оюутолгойд үйлчлүүлэхгүйн тулд энэ хуулийг өөрчилсөн ч байж болно шүү дээ. Түүнийг орлох татвар байх ёстой гэж УИХ шийдсэн. Тиймээс Гэнэтийн ашгийн татварыг орлож гарч ирсэн Өсөн нэмэгдэх роялтийг төлөх нь зүйтэй. “Эрдэнэт” гэдэг компани төлөх нь байна. “Оюутолгой”-гоос хойш гарч ирэх “Эрдэнэс Тавантолгой” ч юм уу, бусад компани төлөх нь байна. Тэгэхээр “Оюутолгой” яагаад төлөхгүй гэж. Магадгүй, Өсөн нэмэгдэх нөөцийн төлбөрийг төлснөөр компанид итгэх итгэл нэмэгдэж, компанийн байр суурийг улам бэхжүүлэх ч юм бил үү. “Оюутолгой” компанийнхан, бид нийгмийн лиценз гэдэг зүйлийг авна гэж ярьдаг шүү дээ. Тэр нийгмийн лиценз гэдэг нэр хүндийг авахад энэ төлбөрийг төлөх нь онцгой ач холбогдолтой. Магадгүй, зэс, алтны үнэ дахиад өснө. Тэр үед өөр улстөрчид гараад ирчихсэн, зарим улс төрч нь эргээд Оюутолгой руугаа дайрна. Нийгэмд тогтворгүй байдал үүснэ. Эргээд төсөлдөө тогтворгүй байдал үүсгэхийг ч үгүйсгэх аргагүй. Тэгэхээр компанидаа ч гэсэн ашигтай зүйл биш. Хэрвээ энэ төлбөрийг төлөх талаар Оюутолгойн гэрээнд өөрчлөлт хийж, оруулж чадвал аль аль талдаа ашигтай зүйл болно байх. Иймэрхүү зүйлсийг эхний ээлжинд ярилцмаар санагддаг юм. Төр, засгийнхан маань чухам юү гэж бодож явдгийг мэдэхгүй юм.

Оюутолгойн гэрээний энэ мэт учир дутагдалтай зүйлс улс төрийн шийдлээс болж байна уу, эсвэл гэрээний мэргэжилтнүүдийн маань чадвар, туршлагаас шалтгаалж байна уу?

Ний нуугүй хэлэхэд, аль алинд нь л байгаа байх. Мэдээж хэрэг, Оюутолгой монголчуудын хувьд хамгийн том гэрээ. “Эрдэнэт”-тэй зүйрлэж ярьдаг л даа. Нөхцөл нь их өөр шүү дээ. Ялангуяа улс төрийн нөхцөл шал өөр. Зарим улстөрч “Эрдэнэт”-тэй харьцуулахад Оюутолгойн гэрээ маш сайн болсон гэж ярьдаг. Монголчууд “Эрдэнэт”ээс үнэхээр их юм авсан юм бол менежментийн төлбөрийг тийм өндөрөөр төлөх ёсгүй биз дээ. Энэ чинь бид бас ч гэж өөрсдөө уул уурхай хийгээд үзчихсэн, тодорхой чадвартай болчихсон гэсэн үг биз дээ. Яахав, “Рио Тинто”-гоос бага зэргийн менежментийн ур чадвар авна гэдэг утгаараа бага зэргийн төлбөр төлөх ёстой. Гэтэл одоо “Эрдэнэт” гээд 30 жил уул уурхай ажиллуулчихсан мөртлөө дахиад л “Рио Тинто”-гоор маш өндөр үнээр уул уурхай заалгуулах гээд сууж байна шүү дээ. Мэргэжилтнүүдийн хувьд анхны том хэмжээний гэрээ. Гэрээ байгуулах Ажлын хэсэгт хэн орсныг бүгдээрээ л мэдэж байгаа. Мэдээж сайн хүмүүс байгаа. Хамгийн гол нь туршлага байгаагүй. Хоёрдугаарт, тухайн үед манай улс төрчид энэ гэрээг монголчууд нэг баг болж ажиллаж байж сайн гэрээ болгоно. Тийм ч учраас хамтарсан Засгийн газар байгуулж байна гэж тайлбарлаж байсан. Яг нэг баг болж чадсан уу, үгүй юү. Ганц хоёр зүйлээр жишээ авъя л даа. Монгол улс гэрээг 2010 оны аравдугаар сард байгуулсан. Арванхоёрдугаар сардаа Татварын хуульд өөрчлөлт оруулсан. Түүгээр хөрөнгө оруулалтын татварын хөнгөлөлтийг байхгүй болгосон. Гадаадын хөрөнгө оруулагч тэргүүлэх ач холбогдолтой салбарт хөрөнгө оруулах юм бол 10 хувийг нь татвараас чөлөөлөх бололцоотой гэсэн утгатай заалт л даа. Гэрээ хэлэлцээр хийж байх явцад буюу 6-7 дугаар сард УИХ-д өргөн барьсан хувилбаруудад хөрөнгө оруулалтын хөнгөлөлтийн талаар байгаагүй юм. Бүр өмнө нь яригдаж байгаад манай тал зөвшөөрөөгүй учраас орхигдсон байсан. Гэтэл долдугаар сард Нэмүү өртөгийн албан татварын хуульд өөрчлөлт оруулсан байдаг. Тэр нь уул уурхайн компаниуд Нэмүү өртөгийн албан татварын буцаан төлбөр гэдэг зүйлийг авах бололцоог хаасан өөрчлөлт байгаа юм. “Оюутолгой” шиг том компанитай гэрээ байгуулах гэж байна. Хуулиа ингээд өөрчилчихье. Тэгвэл “Оюутолгой”-гоос нэмэлт 500 сая доллар Монгол улсад орж ирэх юм байна гэж тооцоолсон байхыг үгүйсгэхгүй. Хуульд өөрчлөлт орсны дараа нь наймдугаар сард гэрээ хэлэлцээр хийгдлээ. Тэр үед манай хууль өөрчлөгдсөн тул хуулийн дагуу явна гээд Монголын тал асуудлыг тавингуут нөгөө тал болж байна, гэхдээ бид хөрөнгө оруулалтын хөнгөлөлт гэдэг зүйлийг эдэлнэ гээд тулгачихаж байгаа юм. Хэрвээ арванхоёрдугаар сард өөрчилсөн хуулиа долдугаар сард хамт өөрчлөөд, хөрөнгө оруулалтын хөнгөлөлт байхгүй гээд заачихсан бол гэрээ хийж байгаа хүмүүст наймаалцах асуудал үүсэхгүй. Магадгүй, Монголд 400-500 сая доллар илүү орж ирэх тооцоо байсан л байх. Гэтэл хөрөнгө оруулалтын хөнгөлөлт эдлэхээр 5 тэрбумын хөрөнгө орууллаа гэхэд түүний 10 хувь гээд үндсэндээ 500 сая доллар болчихож байна. Монголчууд хоорондоо буюу гэрээ хэлэлцээр хийж байгаа баг нь, УИХ, Засгийн газар ийм байдлаар уялдаагүй ажилласны нэг жишээ энэ. УИХ энэ гэрээг ингэж байгуул гээд тогтоол шийдвэрээ гаргачихсан. Одоо Засгийн газар түүнийг биелүүлсэн үү, үгүй юү гээд л маргалдаж байна шүү дээ.

Биелүүлээгүй бол яах вэ?

Одоо бол бүх л зүйл хөдөлчихсөн байна. Бас л монголчууд нэг баг болж ажиллаж чадаагүйн жишээ.

Энэ бүхэн гэрээ хэлэлцээр яаж хийх талаар эрх зүйн зохицуулалт манайд учир дутагдалтай байгааг харуулж байна уу?

Ер нь гэрээ хэлэлцээр яаж хийх талаар эрх зүйн зохицуулалтыг их сайжруулж өгөх ёстой юм. Гэрээ хэлэлцээр хийж болно. Түүнийгээ ил тод байлгах хэрэгтэй. Тавантолгой дээр гэхэд л ямар гэрээ хэлэлцээр хийж байгааг хүмүүс мэдэхгүй байна. Сайхан сайхан нэр хэлээд, том том компаниуд байна л гээд байдаг. Нөхцөлүүдээ ил болгочихвол бид алдана гэж албаны хүмүүс нь хэлдэг. Нууцлах зүйл байхыг үгүйсгэхгүй. Гэхдээ ерөнхий хэлэлцээр хийх хүрээ нь ямар байгаа юм, үндсэн нөхцөлүүд нь юу юм гэдгээ хуулийн дагуу байлгах ёстой. Тэр нь хуулинд байж байх ёстой. Наймаалцахгүй зүйл гэж байх ёстой. Тэр наймаалцахгүй зүйлсээ бүгдийг ил хэлчих хэрэгтэй. Наймаалцах жижиг сажиг зүйл байхыг үгүйсгэхгүй. Түүнийгээ нууцалдаг л юм байгаа биз. Гэхдээ эцсийн дүндээ гэрээг гарын үсэг зурсны дараа заавал ил болгох ёстой. Яагаад Хөрөнгө оруулалтын гэрээг ил болгочихоод Хувь нийлүүлэгчдийн гэрээг ил болгохгүй байна. Тухайлбал, Тавантолгой дээр оператор компанитай ч юм уу үйлчилгээ үзүүлэх гэрээ хийх нь байна л даа. Түүнийгээ хоёр аж ахуйн нэгжийн хэрэг, өөрөөр хэлбэл “Эрдэнэс МГЛ” төрийн өмчит компани болон өөр нэг компанийн хоорондын хэрэг гээд бас ил болгохгүй байх уу. Цаана нь эргээд л олон нийтийн өмч гэдэг асуудал яригдана. Ганц энэ шалтгаан л гэрээг заавал ил болгох шаардлага болж байгаа юм. Нөгөө талаасаа гэрээ ил болно гэдгийг мэдэж байвал хийж байгаа хүмүүс нь илүү хариуцлагатай хандах болно. Дараа ямар гэрээ байгуулсныг ард түмэн шүүнэ гэдгийг мэдэж байгаа хүний асуудалд хандах хандлага хүртэл өөрчлөгдөнө. Тэгж байж хариуцлага гэж яригдаад байгаа зүйл үүсэх болов уу гэж би боддог юм. Гэрээнүүдийг заавал ил болгох хууль тогтоомж, эрх зүйн орчин хэрэгтэй байна. Одоо Ашигт малтмалын хуулийг өөрчлөх тухай ид яригдаж байна. Түүнд гэрээнүүдийг ил болгох асуудлыг оруулах ёстой. Жаахан халиад ярихад, Монголд Оюутолгойн Хөрөнгө оруулалтын гэрээ гэж байгаа. Уул уурхайд Тогтвортой байдлын тухай гэрээ гэж бий. Тогтвортой байдлын гэрээг үндсэндээ арваад жилийн дараа, ач холбогдол нь буурчихсан хойно л олон нийт ямар гэрээ байгуулагдсаныг мэдэж авлаа шүү дээ. Өмнө нь мэдэх арга байсангүй. Дээрээс нь “Эрдэнэт үйлдвэр”, Монголросцветмет” гээд Засгийн газар хоорондын хэлэлцээрээр явдаг аж ахуйн нэгжүүд байна. Тэд ямар нөхцөлөөр явдагийг хэн ч мэдэхгүй. Хэдэн мундаг хүмүүс, мэргэжилтнүүд нь л хааяа нэг тэр гэрээнд тийм зүйл орсон гэж ярьдгаас биш тэр гэрээг нь хэн ч үзээгүй. Газрын тосны салбарт гэхэд Бүтээгдэхүүн хуваах 10 гаруй гэрээ байна. Бүгд хаалттай. Ер нь нийтийн өмчийг хаалттай хэлбэрээр зарцуулдаг энэ байдлаар удаан явахгүй ээ. Энд эргээд л эзэн менежер хоёрын хоорондын зөрчлийн асуудал гарч ирж байна. Эзэн нь ард түмэн байдаг, менежер нь төр засаг байдаг. Эзэндээ баялгийг нь, өмчийг нь яаж зарцуулж байгаагаа менежер харуулахыг хүсэхгүй байна шүү дээ. Ийм байдлаар асуудалд хандаж болохгүй л дээ. Манайд мэдээллийн эрх чөлөөний тухай хууль гэж алга. Бидний жишээ татах дуртай Норвеги улсад гэхэд хувь хүн тухайн жилд ямар орлого олсон, хэдийг нь татварт төлснийг вэб сайтаас хэн ч ороод үзэх боломжтой. Нийгэмд нь тийм их итгэлцэл тогтсон байна. Тэр нийгэмд хүн би ийм ажил хийгээд, ийм ашиг олоод явж байна гэдгээсээ айх биш харин ч бахархаж байна. Монголд бол эсрэгээрээ. Хувь хүний татварыг нь больё л доо. Харин уул уурхай бол онцгой бизнес. Олон нийтийн эрх ашигт шууд нөлөөлдөг, олон нийтийн өмч дээр тулгуурласан бизнес. Дээрээс нь манайх шиг жижигхэн улсад уул уурхай эргээд төр засгийн шийдвэрт нөлөөлөх маш хүчтэй лобби болж хувирдаг. Нөгөө л баялгийн хараал энэ тэрийг тойрч гарах гээд байгаа бол ил тод байх дээр онцгой анхаарах ёстой. Мөн гэрээ хэлэлцээрийг цаашид яаж явуулах вэ, ямар түвшинд гэрээ хэлэлцээр хийх хүмүүсээ бэлтгэж сургах вэ, ямар түвшинд тэр хүмүүсээ ажиллуулах вэ гэдгээ ч бодох ёстой юм.