---
title: "Мөнхийн сэдэв ОТ"
format: html
---

Арнауд Суарат гэгч Рио Тинтогийн зэс, очир эрдэнийн бүлгийг хариуцсан захирлын"Монгол Улсын эдийн засгийн өсөлтөд Оюу толгой хэрхэн нөлөөлж чадах вэ?" гарчигт нийтлэл "Өдрийн сонин"-ны 2019 оны 5 сарын 2-ны өдрийн дугаарт гарчээ. Товчхондоо бол Монгол Улсын төр засгийн өндөр албан тушаалтнууд Оюу толгойн гэрээг хянах, хөндөх тухай асуудлыг сүүлийн үед их ярих болсон бөгөөд байгуулсан гэрээнүүдийг огтхон ч өөрчлөхгүй тухай сүржин мэдэгджээ. Оюу толгойн талаар олон хүмүүс элдэв зүйл ярьдаг ч тэр бүр санаа оноогоо цэгцэлж нэгтгэн, бичсэн нь үгүй тул жаахан тэмдэглэл хөтлөе гэж бодлоо.

Мэдэгдлийн гарчигаас л харахад Рио Тинто "ууртай" байгаа нь илт. Оюу толгой Монголын жижигхэн эдийн засагт эерэг нөлөөлөх тухай олон жил ярьсан. Төлсөн татвар, ханган нийлүүлэлт, ажлын байр нэмэгдүүлсэн зэргээс энэ удаад ч дурьджээ. Гэхдээ бас өсгөж болсон юм, унагаж бас чадна шүү гэсэн өнгө аяс илт. Хөрөнгө оруулагчдын газрын зургаас Монголыг баллах, блокчлон олборлохыг Рио Тинтогоос өөр компани хийж чадахгүй, 20 том санхүүгийн байгууллага тэдний талд бий, асуудал үүсвэл 12 тэрбум доллар төлөөсөнд нь Монголоос гаргуулах гэх зэргийг сүрдүүлэг, үнэний хослол гэж ойлгож болох ч тэдний өөрсдийн олон жил бага багаар бүрдүүлсэн, Монголд тулгасан бодит нөхцөл гэж харж болох юм.

Түүнчлэн мэдээж Оюу толгойн асуудлууд бол Монголын эрх баригчдаас болж үүсэж буй бөгөөд Рио Тинтод халдаах зүйл байхгүй, эсхүл байлаа ч мэдэгдэлд огт дурдаагүй гэж ойлгохоор байна. Шалгалтыг давхардуулдаг, аудит хийх гэдэг, эрчим хүч зэрэгт туйлбаргүй, уурхайг улс төрийн өрөг дэх шатрын хүү болгодог зэрэг буруушаалт. Харин Риогийн хувьд бол ажиллах сайн арга барил, өндөр ёс зүйтэйгээ дурджээ.

Цааш уншвал Риогийн том дарга байр сууриа ихэд шулуухан илэрхийлсэн, Монголд олон дахин буюу жилийн дотор 11 удаа "айлчилж" цаг заваа гарздаж байгаадаа гомдоллосон нь Монголын улс төр, нийгмийн хандлагаас залхаж буйн шинж биз. Үнэхээр ч Оюу толгой бол манай улс төрчдийн дуртай сэдэв бөгөөд сонгууль ойртох тусам улам их яригдах нь ойлгомжтой. Том төсөл учраас ярих, магтах, шүүмжлэх сэдэв ч мундахгүй.

Оюу толгойг бид бүгд ОТ гэж товчлон нэрлэх дуртай. Англиар "overtime" буюу "нэмэлт цаг" гэдэг үгийг бас ийнхүү товчлох нь элбэг байдаг. Үнэхээр ч Оюу толгой бол талуудын цаг сунган зууралдах шатрын өрөг гэлтэй. Олон тэрбум долларын хөрөнгө оруулалт хийгдсэн тул аливаа асуудал үүсэхэд талууд зууралдахаас аргагүй. Оруулах хөрөнгө оруулалт нь 12 тэрбум доллар болохыг мөн уг мэдэгдлээс харж болно.