---
title: "ОТ ногоон гэрэл"
format: html
---

2010-4-1

Оюутолгойн гэрээг Засгийн газар хүчин төгөлдөр хэмээн зарлалаа. Хугацаанаас нь 7 хоногийн өмнө ийн яаран зарласанд мэдээж УИХ дээр дахин асуудал үүсэхээс сэргийлсэнийх байх. Ямар ч л байсан манай эдийн засгийн дүр төрхийг тодорхойлох төсөл урагшлах нь тодорхой.

Харин Засгийн газрын хоёр сайдын тайлбараас анхаарал татсан асуудлууд байлаа. Манай улс төслийн нийт өнөөгийн үнэ цэнийн 66 хувийг хүртэнэ гэж ТЭЗҮ-д заасан гэж толгой эргүүлэв. 66 хувийг монголын тал авна гэсэн үг ОТ-н хөрөнгө оруулалтын гэрээнд байхгүй. 66-н хувийг авч ч магад, авахгүй ч байж магад. Бүр нарийн тооцвол 66 хувиа авах магадлал бага. Харин нөгөө тал 34 хувиа авах магадлал бол бараг 100 хувь. Харин түүнээс дээш хувь хүртэх магадлал мөн их. Хүмүүсийг төөрөгдүүлсэн мэдэгдэл хийсэн гэж хэлж болно. За УИХ-ын гишүүд ямар тоо ойлгох биш нарийн тоо танилцуулаад хэрэггүй гэж үздэг хүмүүс энгийн иргэдэд бол бүр энгийн мэдээлэл л өгнө биз дээ.

Татварын урьдчилгаа төлбөр зээл болсонд хариу өгөхдөө энэ нь ямар ч ялгаагүй мэт тайлбарлах юм. Зээл гэдэг бол заавал тодорхой хугацаанд эргэн төлөх нөхцөлтэй байдаг. Харин татварын урьдчилгаа бол тухай татварыг төлөх нөхцөл бүрэлдээгүй бол тийм нөхцөл бий болтол эргэн төлөлт нь хойшлоод л байх, бүр зарим тохиолдолд огт эргэн төлөгдөхгүй байж болох зүйл. Ялгаа байгаа биз...

За ямар ч л байсан ОТ-д амжилт хүсье. Үнэхээр 66 хувийг аваасай л гэхээс. Юу л болдоо...