---
title: "ot_soon"
format: html
---

2009-7-5

Оюутолгойн гэрээ удахгүй батлагдах бололтой

Олон жил яригдсан Оюутолгойн гэрээ удахгүй батлагдах бололтой. Ямар ч байсан Засгийн газар, УИХ-ын намын бүлгүүд энэ гэрээг хурдхан батлах нь зөв гэж үзэж байгаа нь ажиглагдаж байна. Харин хэдхэн сарын өмнө олон нийтийн, мөн УИХ-ын гишүүдийн ихээхэн эсэргүүцэлтэй тулгарсан гэрээний төсөлд ямар өөрчлөлтүүд орсон нь тийм ч тодорхой биш байна. Тиймээс анхаарч үзсэн байгаасаа гэсэн зарим асуудлын талаар энд бичив.

Өмнөх гэрээний төслийн нэгэн томоохон асуудал бол урьдчилгаа төлбөр болон Монголын талын ирээдүйд хийх хөрөнгийн эх үүсвэрт тооцох хүүгийн хэмжээ их өндөр байсан явдал. Тухайлбал, 9.9 хувь дээр АНУ-ын хэрэглээний үнийн индэксийг нэмсэн хэмжээнд Айвенхоуд хүү төлөхөөр тохирсон байсан. Энэ нь нэгдүгээрт өндөр хэмжээтэй хүү, хоёрдугаарт хэрэглээний үнийн индекстэй хүүг холбох нь Монголын талын хүлээх эрсдлийг нэмэгдүүлж байгаа. Адаглаад ХҮИ биш ДНБ-ний дефлятор хэмээх үзүүлэлтээр инфляцийг тооцох нь зөв юм.

Өөр нэг асуудал бол ногдол ашгийн суутгал татварыг чөлөөлж, менежментийн төлбөр хэмээх их өндөр хэмжээтэй төлбөрийг төлөхөөр тохирсон явдлыг өөрчлөх шаардлагатай юм. Ийм өндөр хэмжээний менежментийн төлбөрийг дэлхийн аль ч улсад төлдөггүй гэдгээ Рио өөрөө хүртэл хүлээн зөвшөөрч байгаа. Өндөр төлбөрийн жишиг тогтоох нь баялаг ихтэй манай улсад алсдаа ч таатай зүйл яав ч биш. Тэгээд ч бид 34 хувийг эзэмшлээ гээд ямар нэгэн эрх нэмэгдэж байгаа зүйл үнэн хэрэгтээ байхгүй шүү дээ. Учир нь 34 хувиа бид өндөр хүүтэй зээл хэлбэрээр санхүүжүүлж байгаа, мөн удирдлагын шийдвэрт оролцох боломжгүй байгаа. Тиймээс 34 хувь эзэмшсэний төлөө бид ямар нэгэн татварын буулт хийх нь зохисгүй юм.

Ногдол ашгийн суутгал татвар уг нь хуулинд 20 хувьтай, харин Канад Монголын тохиролцоогоор бол 5 хувь. Энэ нь олон асуудлыг үүсгэж байгаа зүйл юм. Тухайлбал, давуу эрхтэй хувьцааг зөвхөн Айвенхоу өөртөө гаргаж, Монголын тал ногдол ашиг авахаас өмнө өөртөө ихээхэн ашиг хүртэх боломжийг олгож байгаа. Ер нь өнөөгийн гэрээний нөхцлөөр ашгаас Монголд орох орлого цаашилсаар л байна. Үндсэндээ Айвенхоу бүх оруулсан хөрөнгөдөө 14 орчим хувийн ашиг хүртсэний дараа л бид тэдэнтэй ашгаас нь хуваалцах тухай асуудал яригдаж байна.

Энэ мэтийн олон асуудал байгаа. Энэ бүгдийг гэрээнд хэрхэн зохицуулахыг хэлж мэдэхгүй байна. Ямартаа ч манайд томоохон гэрээ хийхэд үнэхээр хүндрэлтэй олон хүчин зүйл байгааг энэ хэлэлцээ харуулж байна. Энд шийдвэр гаргах механизм төвөгтэй, чадавхи сул, нээлттэй ил тод биш учир иргэдийн итгэлийг хүлээх чадваргүй байдал зэргийг нэрлэж болох юм.