---
title: "slide_further"
format: html
---
2010-6-11

Цааш дампуурах боломж байна уу?

Эдийн засаг сүйрлээ гэж нэг УИХ-ын гишүүн ярьжээ. Төр болохоо байлаа гэж маш олон хүн ярьж байна. Үнэхээр орчноо хараад байвал цааш дампуурах боломжгүй болж байх шиг байна.

УИХ-ын чуулган дээр төсвийн гүйцэтгэлийг хэлэлцэж байна. Сангийн сайд нь 2.5 тэрбум төгрөгийг аргагүй байдалд ороод өөрөө дур мэдээд зарцуулчихсан гэж байх юм. Тэр сайд ажлаа хийсээр. Төсвийг хэтрүүлэн зарсан гэх юм. Уг нь төсөв гэдэг хууль. Хууль зөрчсөнөө огт тоохгүй ярьж байгаа олон хүн байх юм. Өөр нэг газар хэмнэлт гаргасан юм чинь яадаг юм гэх юм. Хэмнэлт гаргах нь уг нь бас хийх ёстой ажил хийгдээгүйг л илтгэмээр юм.

Төв банк бодлогын хүүгээ нэмлээ гээд УИХ Засгийн газартайгаа нийлж байгаад авч өгч байнаа. Бодит эдийн засагт мөнгө хүрэлцэхгүй байхад хүүгээ бууруулах ёстой юм гэнэ. Өөрсдөө нийлж байгаад эх орны хишиг гэж  нийлүүлэлттэй огт уялдаагүй баахан бэлэн мөнгө тараачихсан, удахгүй цалин нэмнэ гээд амалчихсан, хүүхдийн мөнгийг хоёр дахин нэмэгдүүлж дахин өгөх тухай ярьж байгаа улсууд үнийн өсөлтийг хязгаарлахгүй бол болохгүй шүү дээ гэх банкны ерөнхийлөгчийг зүхэх юм. Банкны хадгаламжид хавтгай баталгаа гаргасан, Хадгаламж, Анод, Зоос банкны алдагдлыг татвар төлөгчийн мөнгөөр төлсөн, төв банкыг нь гадаад дотоодод төрийн гэх банктай андуурахад хүртэл сэтгэж чаддаг УИХ, Засгийн газар хоёр шүү. Төрийн банк дээрээ нэмээд хөгжлийн банк байгуулах гэж байгааг бас дурьдах хэрэгтэй байх. Төсвийн хариуцлагыг дээшлүүлж хууль батлах юм гэнэ. Хөгжлийн гэх банк байгуулчихаад төсвөөс гадуур маш их санхүүгийн эх үүсвэртэй болох тул тэр хууль батлагдсан батлагдаагүй тэдний эрх мэдэл сулрахгүй нь.

Тавантолгойн лицензийг 8 жил хадгалж ард түмэндээ өгсөнд Ерөнхий сайдад баярлалаа гэмээр байна гэж УИХ-ын хэд хэдэн гишүүн долигонож байх юм. Баярлалаа л гээч дээ, гэмээр байна ч байхдаа яахав дээ. Олон компани өндөр үнээр авая гэхэд нь ард түмнээ бодоод харамласан юм гэнэ. Юмыг яаж мэдэхэв, Ерөнхий сайд ч болчих юм билүү гэж л тэр лицензээ буцааж өгөө биз дээ. Буцааж өгөөгүй бол ард түмэн босоход бэлэн байсан гэхэд хэтрүүлээгүй л болов уу.

Үнэ буулгадаг мундаг туршлага Монголд байна. Хувьчлалыг практикт байтугай ямар нэгэн онолд ч байхгүй хувилбараар Монголд л хийж чадна. Төрийн өмчийг хувийн мэт ашигладаг, ард түмний нэрийг барьж өөрөөсөө бусдаас харамлан ашигладаг нь Монгол. Сум бүртээ хүнсний үйлдвэртэй, тэр үйлдвэр бүр нь нэг л төрлийн бүтээгдэхүүн үйлдвэрлэдэг, үйлдвэрлэл агуу хөгжсөн нь манайх. Хэдэн арван мянгаараа гадаадад боолын хөдөлмөр эрхлэхээр дугаарлаж байхад хэдэн зуун мянгаараа юу ч хийхээс буцахгүй болтлоо боловсорсон хятадууд энд харин ажлаад байна. 10, 20 тэрбумаар нь банкнаасаа гэгээн цагаан өдөр алдчихаад яадаг ч үгүй. Хариуцлага алдвал, хулгай хийвэл улам л дэвшинэ.

Олон юм яриад байвал бүх юмыг хуулийн дагуу болгочихно. Хуулиа өөрсдөө санаачлаад батлуулчихна. Өөртөө зориулсан хуулийг шүү. Бүр болохгүй бол олон улсын гэрээ байгуулчихна. Бүх юм хуулийн дагуу.

Цааш бид уруудах арга байна уу? Орон зай байна уу?