---
title: "tt_interview"
format: html
---

2010-6-17

Өмнийн Говийн Хөгжлийн Зөвлөл

2010 оны 5 дугаар сарын 21-ний Засгийн газрын 124-р тогтоолоор Өмнийн Говийн Хөгжлийн Зөвлөл байгуулагджээ. Оюутолгойн ордыг ашиглах хөрөнгө оруулалтын гэрээний дөрөвдүгээр бүлэгт ийм зөвлөлийг Засгийн газар байгуулахаар заасан байдаг. Зөвлөл нь Өмнөговь аймагт чиглэсэн үйл ажиллагаа явуулдаг удирдах зөвлөлтэй байх бөгөөд түүнд нь иргэний нийгмийн байгууллагууд ч орохоор тогтсон байгаа. Зөвлөлийн үүрэг нь товчхондоо тус аймгийн хөгжлийг төлөвлөх, хөгжилд чиглэсэн үйл ажиллагааг хэрэгжүүлэхэд Засгийн газарт туслах явдал. Харин зөвлөлд яг ямар байгууллага, хувь хүн орохыг гэрээнд нарийн заагаагүй. Тиймээс чухам ямар хүмүүс түүний дотор ялангуяа иргэний нийгмийн байгууллагууд уг зөвлөлд орж ажиллах болсныг сонирхож үзэв.

Уг зөвлөл нь 41 хүний бүрэлдэхүүнтэй, нэг нарийн бичгийн даргатай. Өмнөговь аймгаас сонгогдсон УИХ-ын хоёр гишүүн тус зөвлөлийн хоёр дарга нь. 25 нь ямар нэгэн дарга. Дээр нь нэг орлогч, нэг ахлах референт, хоёр ИТХ-ын төлөөлөгч, гурван ерөнхийлөгч, нэг тэргүүн, зургаан захирал. Нарийн бичиг нь “бүрэн эрхт” төлөөлөгч. Өөрөөр хэлбэл хариуцлагатай албан тушаал хашсан дан дарга нар.

Төрийн байгууллагыг төлөөлж 28, түүнээс 16 нь орон нутгийн засаг захиргаанд алба хашигчид. Мөн 7 компанийн захирал, 2 бизнесийн салбарыг төлөөлсөн төрийн бус байгууллага зөвлөлд орсон байна. Харин иргэний нийгмийг төлөөлүүлж таван байгууллагыг сонгон уг зөвлөлд оруулсан бололтой. Тэд хэн бэ?

Шинэ Ханбогд холбоо ТББ-ын тэргүүн Т. Эрдэнэ-Очир, Залуучуудын хөгжлийн төв ТББ-ын Ч. Буянбаатар, Өмнөговь аймгийн Эмэгтэйчүүдийн зөвлөлийн дарга Х. Байгалмаа, Өмнөговь аймгийн Үйлдвэрчний эвлэлийн холбооны дарга Д. Мөнх-Эрдэнэ, Өмнөговь аймгийн Ахмадын хорооны дарга Б. Бат-Өлзий. Бизнесийг төлөөлж буй хоёр ТББ нь Бизнесийн зөвлөлдөх зөвлөлийн тэргүүн А. Идэрцог, Уул уурхайн үндэсний ассоциацийн ерөнхийлөгч Д. Дамба.  Нэгэнт бизнесийг төлөөлж байгаа учраас иргэний нийгмийн байгууллага гэх оновчгүй байх. Харин Өмнөговьд ажилдаг дээрх таван байгууллага нэрнээс нь харахад үнэхээр иргэний нийгмийн төлөөлөгчид бололтой.

Гэвч тэдний гурав нь даргатай байгууллага байгаа нь анхаарал татаж байна. Өөрөөр хэлбэл социализмын үед байгуулагдсан, магадгүй төсвөөс санхүүждэг байгууллагуудын төлөөлөгчид. Мөн уул уурхайн салбарын талаар хийсэн ажлын туршлага бараг байхгүй байгууллагууд. Цаана нь хоёр ТББ байна. Энэ хоёр нь үнэхээр иргэний нийгмийн байгууллага байгаа гэж найдах л үлдэж. Тийм байсан ч 42 хүний, олон даргатай зөвлөлд энэ хоёр идэвхтэй ажиллах боломж бага л байх.

Засгийн газарт туслах зорилготой энэ байгууллага ямар ч л байсан Өмнийн говийн хөгжилд чухал үүрэгтэй байх эрмэлзэлтэй байх. Аймгийн ИТХ, засаг захиргааны үүрэг бусад аймгийнхаас буурах юм болов уу. Засаглалын хомсдол нэгэнт үүссэн гэх энэ аймагт уг нь байнгын идэвхтэй үйл ажиллагаатай, нээлттэй, чадавхитай төрийн бус байгууллагуудыг оруулсан бол дэм болохгүй юм гэхэд тээг болохгүй л байсан байх. Мэдээж дарга нарыг шийдвэр гаргахад нь элдэв зүйл анхааруулан эсэргүүцэх магадлалтай, үүнээс зөвлөлийг байгуулсан хүмүүс сэрэмжилсэн л байх. Харин одоо байгаа бүрэлдэхүүнд олон дарга нартай эн зэрэгцэн ажиллах бололцоо хомс л байх даа.