---
title: "tt_proposal"
format: html
---

Тавантолгойн нүүрсний ордыг ашиглах саналын талаарх санал шүүмж

010 оны 5 дугаар сарын 31-ний өдөр




Төрийн өмчит Эрдэнэс МГЛ компани ашиглалтын лицензийг нь эзэмшиж буй Тавантолгойн нүүрсний ордыг ашиглахдаа хөрөнгө оруулагчдыг хэрхэн татан оролцуулах саналаа Засгийн газар гаргажээ. Чингэхдээ тус ордыг хэд хэдэн хэсэгт хувааж, хөрөнгө оруулагчдын техникийн болон санхүүгийн саналд үндэслэн урьдчилан сонгон шалгаруулалт хийж 5-7 компани шалгаруулах ба тэдгээртэй бүтээгдэхүүн хуваах хэлбэрийн дагуу хамтран ажиллах санал тавьж, хэлэлцээ хийсний үндсэн дээр хөрөнгө оруулагчдыг эцэслэн шийдвэрлэхээр төлөвлөж байгаа аж.

Энэхүү саналтай холбоотой товч санал дүгнэлт бэлтгэснээ толилуулж байна. Төслийн үр ашгийг тооцоход шаардлагатай олон үзүүлэлт, тухайлбал дэд бүтэц, болзошгүй оролцогчдын санал нь тодорхой бус, уул уурхайн салбарт бүтээгдэхүүн хуваах зарчмаар орд газрыг ашиглах эрх зүйн орчин, туршлага манай улсын хувьд байхгүй зэргээс хамаарч төслийн үр ашиг, эрсдэл хуваарилалтын талаар тодорхой санал илэрхийлэх боломжгүй байна. Энэ санал дүгнэлтийг бэлтгэхдээ Тавантолгойн ордыг гэрээний бусад хэлбэр, тухайлбал концессийн гэрээний дагуу ашиглах боломжтой харьцуулах зорилтыг тавиагүй болно.

Хөрөнгө оруулалтын гэрээтэй холбоотой асуудлууд

Оролцогч талууд

Хөрөнгө оруулалтын гэрээг Засгийн газар, Эрдэнэс МГЛ төрийн өмчит компани, хөрөнгө оруулагч гэсэн гурван талын хооронд байгуулахаар төлөвлөжээ. Түүнчлэн Тавантолгойн нүүрсний ордыг ашиглах зарим асуудлын тухай УИХ-ын тогтоолын төсөлд ордын тодорхой хэсэгт төрийн өмчит компани олборлолт, ашиглалтын үйл ажиллагааг явуулахаар төлөвлөсөн байна.

Хөрөнгө оруулагч нь Монгол Улсад бүртгэлтэй (Хөрөнгө оруулалтын гэрээ \ХО\-ний 1.26) байхаар заасан нь өөрийн хөрөнгө багатай салбар компани сонгон шалгаруулах магадлал өндөр байна. Иймээс хөрөнгө оруулагчийн оруулах хөрөнгө, ашиглах технологи, мөн байгаль орчныг хамгаалах, нөхөн сэргээх, уурхайг хаах талаарх үүргүүдийг толгой компани нь давхар хариуцахаар баталгаажуулах асуудлыг гэрээнд тусгах нь зүйтэй юм.

Ордын тодорхой хэсгийг төрийн өмчит компани олборлох, ашиглах нь төдийлөн оновчтой бус байна. Хэрэв ийм компани байх шаардлагатай бол тэр нь Эрдэнэс МГЛ-ээс тусдаа байх нь зохимжтой юм. Эрдэнэс МГЛ нь оператор бус зөвхөн холдинг компани байснаар ашиг сонирхлын зөрчил үүсэхээс сэргийлнэ. Харин өөр нэгэн төрийн өмчит компани ашиглалт явуулах бол төсвийн хөрөнгийг уул уурхайн салбарт хэт төвлөрүүлж, эдийн засгийг олон тулгуурт болгох бодлоготой харшлахаас гадна хувийн болон гадны хөрөнгө оруулагчдад аль болох өндөр үнэ хүргэн нүүрс олборлох эрхийг худалдахаас олох орлогыг хаах тул ерөнхий дүнгээрээ төсөвт алдагдалтай тусах боломжтой юм. Тэгээд ч төрийн өмчит компанийн засаглал, үр ашгийн асуудал хөндүүр сэдэв гэдгийг ч бодолцох учиртай биз ээ.

Эрдэнэс МГЛ нь хөрөнгө оруулагчийн үндсэн болон санхүүгийн үйл ажиллагаанд хяналт тавьж ажиллахаар заасан байна (ХО 6.1). Харин Засгийн газрын эрх үүргийг тодорхойлохдоо (ХО 7-р бүлэг) татвар, байгаль орчин, хөдөлмөр эрхлэлт зэрэгтэй холбоотой харилцааг шууд хянах боломжийг зааж өгөөгүй нь хяналтын чиг үүргээ зөвхөн төрийн өмчит компаниар дамжуулан хэрэгжүүлэхээр ойлгогдож байна. Эрдэнэс МГЛ-ийн хувьд хөрөнгө оруулагч аль болох ашигтай ажиллаж, илүү бүтээгдэхүүн түүнтэй хуваалцах сонирхол нь давамгайлж болох тул төрийн хяналтын чиг үүргийг бүгдийг нь тус компанид шилжүүлэх нь зохимжгүй юм. Хяналтын болон эрх олгох (орлого олох) чиг үүргийг салгаж өгөхийн ач холбогдлыг харуулсан ойрын жишээ БиПи Пи Эл Си компани Мексикийн булангийн цооногийн ослоос далайд их хэмжээний газрын тос алдсан явдал орно. Энэ гамшгийн улмаас АНУ-ын Уурхай, эрдэс баялгийн албын орлого олох болон хяналтын чиг үүргийг нь салгаж, дотоод сонирхлын зөрчлийг арилгах талаар эдүгээ ид яригдаж байна.

Татварын орчин

Хөрөнгө оруулагч Монгол Улсад үйлчилж буй бүх төрлийн татварыг төлөхөөр заажээ. Ингэхдээ зарим татварын хувь хэмжээ болон тооцох суурийг тогтвортой байлгахаар харагдаж байна. Тогтворжуулах татварын тоог цөөн байлгаснаар ирээдүйд татварын бодлогоор эдийн засгийг бүхэлд нь удирдах боломжоо Засгийн газрын хувьд хязгаарлуулахаас сэргийлнэ. Нэмэгдсэн өртгийн албан татвар, гаалийн татвар хоёрыг тусгайлан авч үзэж тогтворжуулсан (ХО 3.5 ба 3.6) ба харин бусад татварын хувьд хэлэлцээний үндсэн дээр тогтворжуулах эсэхийг шийдэхээр байгаагийн үндэслэл юу болох нь ойлгомжгүй байна.

Нөөц ашигласны төлбөрийг төрийн өмчит компаниар дамжуулан төсөвт төлөхөөр заажээ. Ашигт малтмалын хуулийн дагуу энэ төлбөрийг ашигт малтмалын тусгай зөвшөөрөл эзэмшигч болох Эрдэнэс МГЛ төлөх ёстой ч энэ компани нь Оюутолгойн ордын тодорхой хувь зэрэг төрөл бүрийн активтай байхаас үүдэн гуравдагч талын өмнө ямар нэгэн үүрэг хүлээх нөхцөл үүсвэл нөөц ашигласны төлбөрийг тодорхой хэмжээгээр өөр зорилгод ашиглах, дайчлах нөхцөл үүсч болзошгүйг хязгаарлах шаардлагатай. Түүнчлэн татвар, төлбөр зөв төлөгдөж байгаа эсэхэд татварын алба давхар хяналт тавих нөхцлийг бүрэлдүүлэх шаардлагатай. Тухайлбал, нүүрсийг дотоодод борлуулбал экспортод гаргасантай харьцуулахад хоёр дахин бага хэмжээгээр нөөц ашигласны төлбөрийг төлөх тул (Нүүрс олборлох гэрээ 6.2.3) дундын (цааш нь экспортлох) зуучлагч дотоодын хуулийн этгээдэд нүүрсийг борлуулж, уг төлбөрийг бүрэн төлөхөөс зайлсхийх боломжийг хааж өгөх заалтыг гэрээнд оруулах нь зүйтэй юм.

Нүүрсний борлуулалтаас олсон орлогыг гадаадад чөлөөтэй гаргаж, тэнд нь хадгалах боломжтой байгаа нь гадаад гуйвуулгад ногдуулдаг суутгал татварыг төлөхгүй байх, төлөхөөс өмнө орлогыг зарцуулах боломжийг давхар бүрдүүлж болзошгүй байна.

Хөрөнгө оруулагч Монгол Улсад урьдчилгаа төлбөр төлөх шаардлагатай гэж заасан байгаа ч ямар татвар, төлбөр, хураамж, бүтээгдэхүүнээр энэ урьдчилгаа төлбөрийг эргэн барагдуулах талаар нарийвчлан заагаагүй байна.

Хөрөнгө оруулалтын гэрээнд гарын үсэг зурсны бонус төлбөр авахаар саналд тусгагджээ. Энэ төлбөрийг авах эрх зүйн орчныг бүрдүүлэх, ингэхдээ гэрээ хэлэлцээр байгуулахтай холбогдон гарсан төрөл бүрийн зардлыг цаашид уг төлбөрт бүрэн шингээж байх боломж бүрдэж байна. Нэгэнт хөрөнгө оруулалтын зэрэг олон төрлийн гэрээ байгуулж гадаад дотоодын хөрөнгө оруулагчдад төр баталгаа гаргаж өгч байгаа тул энэ төлбөрийг бэлгэдлийн хувьд ч, төсөвт орох шууд орлогын ач холбогдлыг бодсон ч авч байх нь зохимжтой юм.

Бүтээгдэхүүн хуваалт

Хөрөнгө оруулагчтай бүтээгдэхүүн хуваах хэлбэрээр (татвараас гадна) төслийн үр ашгийг хуваалцахаар гэрээний төсөлд тусгажээ. Ингэхдээ бүтээгдэхүүний тодорхой хэсгийг  Засгийн газар шууд авахаар, харин хөрөнгө оруулагч гаргасан зардлаа нөхөх баталгаагүйгээр хуваалтыг хийхээр төлөвлөжээ. Газрын тосны бүтээгдэхүүн хуваах гэрээний хувьд хөрөнгө оруулагч тал гаргасан зардлаа тодорхой хэмжээнд нөхөх боломж олгодог ба түүний дараа үлдсэн бүтээгдэхүүнийг Засгийн газар, хөрөнгө оруулагч хоёр хуваах хувилбарыг гол төлөв ашигладаг. Хөрөнгө оруулагч тал зардлаа нөхөх баталгааг гаргуулж авахыг эрмэлзэх нь мэдээж. Тавантолгойн ордын хувьд нэгэнт хайгуул хийгдсэн тул хөрөнгө оруулагчийн эрсдэл харьцангуй бага учир дээрх зохицуулалт байж болох талтай ч гагцхүү бүтээгдэхүүнийг ямар харьцаагаар хуваах тал дээр тохиролцоонд хүрэхэд хүндрэлтэй болж, хэт бага хувийг Монголын тал авахад хүргэж болзошгүй. Тиймээс хөрөнгө оруулагч тал зардлаа нөхөх боломжийг олгох, зардлаа нөхсөний дараа Монголын талд ногдох хувь өсөх зэрэг хувилбаруудыг зайлшгүй судлах шаардлагатай. Цаашид бүтээгдэхүүн хуваах зарчмыг ашигт малтмал эрэх, хайх, олборлоход ашиглах тохиолдолд хөрөнгө оруулагч өртгөө нөхөх журмыг тодорхойлох эрх зүйн орчинг бүрдүүлэх хэрэгтэй.

Тогтворжилт ба үл ялгаварлалт

Хөрөнгө оруулалтын гэрээний төсөлд зарим татварыг тогтворжуулахаар, мөн бусад аливаа хууль тогтоомжоор илүү таатай нөхцөл бүрэлдвэл түүнийг хөрөнгө оруулагч эдлэх боломжтой (ХО 19.7) хэмээн дурджээ. Энэ нь үндсэндээ нэг талын тогтворжилт бөгөөд хууль дүрэм таатайгаар өөрчлөгдвөл уг нөхцлийг  хөрөнгө оруулагчид эдлэх боломжтой, харин хууль дүрэм илүү хатуу нөхцөлтэй болвол түүнд хамаарахгүй байхаар байна. Монгол Улсад байгаль хамгаалах, нөхөн сэргээх, уурхайг хаах, ажиллах хүчнийг сургах болон байршуулах, нийгмийн хариуцлагыг дээшлүүлэх зэрэг олон харилцааны хувьд уул уурхайн стандартууд нь тэр бүр олон улсын хэмжээнд хүрч чадаагүй, мөн зарим харилцааны хувьд олон улсын стандартууд ч бүрэн тогтож амжаагүй байгааг бодолцон цөөн тооны санхүүтэй холбоотой хууль журмаас бусдыг тогтворжуулахгүй байх нь чухал. Хэрвээ хууль журмаа тогтворжуулахад хүрвэл энэ нь хоёр талын үйлчлэлтэй байхаар, өөрөөр хэлбэл, хууль журам илүү таатай болвол хөрөнгө оруулагчид энэ таатай нөхцөл хамрахгүй байх, харин илүү таагүй болвол хөрөнгө оруулагч хамгаалагдсан байхаар заах нь зүйтэй юм.

Гэрээ нь зөвхөн уурхай төдийгүй дэд бүтэцтэй холбоотой хөрөнгө оруулагчийн үйл ажиллагааг бүхэлд нь хамрахаар байна. Энэ тохиолдолд тогтворжилтын болон гэрээний бусад заалт дэд бүтцийн төслүүдэд ч хамаарахаар байгаа нь оновчгүй байх талтай. Тиймээс гэрээний санхүүгийн болон бусад заалт зөвхөн уурхайн үйл ажиллагаатай хамаатай байхаар зааглах нь зөв юм. Зам, цахилгаан хангамж зэрэг дэд бүтцэд хамрах стандарт, дүрэм журам нь гэрээнд зааснаас өөр байж болох төдийгүй ирээдүйд ч уурхайн үйл ажиллагаанаас хамааралгүйгээр илүү боловсронгуй болох ёстой. Энэ тохиолдолд хөрөнгө оруулагч ирээдүйд үйлчлэх хууль журам, стандартуудыг мөрдөх учиртай.

Үндсэн үйл ажиллагаатай холбоотой төрөл бүрийн зөвшөөрлийг төрийн байгууллагуудаас авахад нь төр, засгаас хөрөнгө оруулагчид дэмжлэг үзүүлэхээр гэрээний төсөлд заасан байна (ХО 2.2). Энэ бол хөрөнгө оруулагдад тусгайлан хандаж, бусад компанийг ялгаварлаж буй хэлбэр гэж ойлгогдоно. Аливаа зөвшөөрлийг хууль журмын дагуу бусадтай адил олгох нь төр засгийн хувьд зохимжтой. Усны болон газрын төлбөрийг гадаад, дотоодын бусад ашиглагчаас үл ялгаварлах зарчмаар тогтоохоор заасан байна. Говь нутгийн ус Хангайн нутгийнхаас илүү үнэ цэнэтэйн зэрэгцээ дотоодын ахуйн хэрэглээ, уул уурхайн хэрэглээ хоёрын төлбөр өөр байх нь оновчтой юм. Гэтэл усны зохистой хэрэглээг ялгавартай бодлогоор зохицуулах боломжийг гэрээгээр хязгаарлажээ. Цахилгааныг төрөөс хангасан тохиолдолд ч ялгаварлахгүй үнээр хангах нөхцлийг илүү нарийн тодорхойлох боломжтой болно.

Үйл ажиллагаа зогсох болон гэрээ цуцлах нь

Хөрөнгө оруулалтын гэрээний төсөлд уг гэрээ дуусгавар болох нөхцлийг зааж өгсөн ч (ХО 16-р бүлэг) зарим нэгэн асуудал нээлттэй хэвээр байна. Түүнчлэн гэрээний төслийн дагуу уурхайн үл хөдлөх өмч нь хөрөнгө оруулагчийн мэдэлд байхаар заажээ. Бүтэн 30 жилийн хугацаанд хүчинтэй байх гэрээний хувьд хөрөнгө оруулагчаас хамааран үйл ажиллагаа гэнэт зогсвол түүний үүргийг хэн биелүүлэх талаар дэлгэрэнгүй зааж өгөх шаардлагатай. Тухайлбал, үйл ажиллагаа гэнэт зогсвол үйлдвэрийн үл хөдлөх өмч төрд шилжих, Монголын тал хөрөнгө оруулагчийн аливаа нэхэмжлэгч, зээлдэгчээс давуу эрхтэй байх нөхцөл тавьснаар олборлолтын үйл ажиллагааг хэвийн хангах юм. Түүнчлэн хөрөнгө оруулагч үл хөдлөх хөрөнгийг барьцаалах, бусдад шилжүүлэх зэрэгт хязгаарлалт тогтоох шаардлагатай байна.

Уурхайг хаахад зарцуулах хөрөнгийг хаалтаас 10 жилийн өмнөөс эхлэн төвлөрүүлэхээр гэрээнийн төсөлд заасан байгааг (ХО 10.15) өөрчилж, хөрөнгө оруулагч ашигтай ажиллаж эхлэх хугацаа нь түүнээс өмнө байвал тэр үеэс эхлэн хуримтлуулахаар зааж болох юм. Ингэснээр уурхайг гэнэт хаах тохиолдолд санхүүгийн тодорхой эх үүсвэр бүрэлдэх юм.

Бусад асуудал

-          Тавантолгойн ордыг ашиглахдаа ордыг хэсэгчлэн, хэсэг тус бүрт нь хөрөнгө оруулагчдыг хуваарилах бодлогыг төр засаг барьж байгаа бол ингэж хуваах үндэслэл, шалгуур нь ил тод байх шаардлагатай. Түүнчлэн ордыг бүхэлд нь ашиглах эдийн засгийн үр ашгийн тооцоотой харьцуулалт хийх нь зүйтэй. Хэсэгчилсэн тохиолдолд хэсэг тус бүрийг дэс дараатай ашиглах, бүгдийг зэрэг ашиглахын давуу болон сул талууд, эдийн засгийн үр өгөөжийг тооцох шаардлагатай байна.

-          Олон хөрөнгө оруулагчийг Тавантолгой төсөлд оруулснаар хэд хэдэн хөрөнгө оруулалтын гэрээ байгуулагдана гэж ойлгогдож байна. Энэ тохиолдолд хөрөнгө оруулагч бүр нүүрс угаах үйлдвэр барихаар байгаа нь эдийн засгийн хувьд оновчтой эсэхийг тооцож үзэх шаардлагатай. Мөн нүүрс борлуулалтыг ч хөрөнгө оруулагчид тус тусдаа хариуцах нь зохимжтой эсэх нь эргэлзээтэй. Магадгүй нүүрс угаах технологийг хамгийн сайн эзэмшсэн компани бүх хөрөнгө оруулагчийн нүүрсийг угаадаг, дэлхийн зах зээл дээр хамгийн өндөр үнээр нүүрсийг борлуулах боломжтой нэг компани нь борлуулалтын асуудлыг хариуцах нь Монгол Улсын хувьд хамгийн ашигтай хувилбар байж болох юм.

-          Хөрөнгө оруулагч Ашигт малтмалын тухай хуулийн 48-р зүйлийн дагуу мэдээлэл бэлтгэж, түүнийгээ төрийн өмчит компани болон Засгийн газарт хүргүүлэхээр байгаа нь (ХО 4.14) тус зүйлийн зарим мэдээллийг олон нийтэд хүргэх үүргийг биелүүлэхгүй байх нөхцлийг бүрдүүлж болзошгүй байна. Хэдийгээр мэдээллийг олон нийтэд хүргэх үүргийг лиценз эзэмшигч Эрдэнэс МГЛ хүлээх боломжтой ч энэ нь гэрээний төсөлд тусгагдаагүй байна. Мэдээллийг хөрөнгө оруулагч шууд нийтэлбэл уг төсөлтэй холбоотой иргэдийн итгэлийг төрүүлэхэд нэн чухал.

-          Уурхайн эдэлбэрт нэвтрэх, үйл ажиллагааг хянах эрхийг Эрдэнэс МГЛ-ийн төлөөлөгч эдлэхээр заасан байгаа ч Засгийн газар энэ эрхийг шууд хэрэгжүүлэх боломжтой болохыг гэрээнд нэмж тусгаж өгөх нь зүйтэй.

-          Хөрөнгө оруулагч дотоодын хэрэгцээнд бүтээгдэхүүнийг зах зээлийн үнээр нийлүүлэх үүргийг заасан (ХО 4.10) нь сайшаалтай ч “зах зээлийн үнэ” гэдгийг тодорхойлж өгөх шаардлагатай. Тухайлбал, Хятад улс руу экспортлохдоо нэг үнэ ашиглаж, дотоодын хэрэгцээнд нийлүүлэхдээ Японы ч юм уу аль нэг зах зээлийн үнийг ашиглах нөхцлийг үүсгэхгүй байх нь чухал юм.

Сонгон шалгаруулалттай холбоотой асуудлууд

Тавантолгойн ордыг хамтран ашиглах хөрөнгө оруулагчийг сонгохдоо урьдчилан сонгон шалгаруулалт хийж, дараа нь хэлэлцээ хийх замаар үндсэн нөхцлүүдээ тохиролцож, хөрөнгө оруулагчдыг эцэслэн шалгаруулахаар Засгийн газар санал гаргасан гэж ойлгож байна. Энэ хувилбар нь тодорхой давуу талтай байж болох ч олон өрсөлдөгч оролцох сонирхлоо илэрхийлсэн энэ тохиолдолд ордыг хамгийн их үнэд хүргэх боломжийг алдаж мэдэх юм. Хэлэлцээ хийх нь цаг хугацаа, хүчин чармайлт шаардахаас гадна талууд өөрсдийн байр суурийг бэхжүүлэх, эсвэл сулруулах, шинэ нөхцлүүдийг тохиролцох боломжийг нээлттэй орхидог. Ордыг хэдэн хэсэгт хувааж, өөр өөр оролцогчийг оруулах сонирхолтой бол түүнийг сонгон шалгаруулалтын нөхцлүүдээр зохицуулж болох ба харин өрсөлдөөнийг үе шат бүрт аль болох дэмжсэнээр санхүүгийн хувьд хамгийн их ашиг хүртэх боломж Засгийн газарт бий юм.

Урьдчилан сонгон шалгаруулалт хийхдээ хэд хэдэн үзүүлэлтээр оноо өгөхөөр Засгийн газар санал болгожээ. Сонгон шалгаруулалтыг ийм олон үзүүлэлтээр хийх нь шилдэг туршлага биш бөгөөд шалгарсан компаниуд хамгийн өндөр үнэ төлөхгүй байх магадлалтай. Мөн ямар үзүүлэлтүүд нь эцсийн үнэлгээнд илүү хувийн жинтэйгээр нөлөөлөх нь тодорхой бус байна. Урьдчилгаа төлбөр, гарын үсэг зурсны бонус зэрэг шууд авах бэлэн мөнгө нь улс төрийн амлалтуудыг биелүүлэхэд дөхөмтэй тул эцсийн үнэлгээнд илүү нөлөө үзүүлэх байдлаар сонгон шалгаруулалтыг хийвэл бололцооны дээд түвшинд Монголын талд ашгаа өгөхөөр гэрээг тохиролцож чадахгүйд хүргэх аюултай.

Нөгөө талаар, тендерийн хүрээнд хөрөнгө оруулагчийн гаргаж өгөх мэдээлэлд байгаль орчныг хамгаалах, нөхөн сэргээх зэрэг зардлын тооцоо орсон нь ойлгомжгүй бөгөөд байгаль хамгаалах, нөхөн сэргээх зардлыг бодит бус, тендерт өгсөн саналын дагуу санхүүжүүлэх мэт ойлголт төрүүлж байна. Түүнчлэн төмөр замын ямар хэсэгт хөрөнгө оруулах сонирхолтойгоо тендерийн материалд хөрөнгө оруулагч илэрхийлэхээр байгаа нь энэ чухал асуудлаар төр, засгийн бодлогыг хөрөнгө оруулагч дагах бус, хөрөнгө оруулагчийн сонирхлоос шууд хамааран төр, засаг бодлогоо тодорхойлох мэт хардлага төрүүлж байна.